/*
 * Copyright (C) 2007-2008 Luís Reis <luiscubal@gmail.com>
 * Copyright (C) 2007-2008 TGMG <thegamemakerguru@hotmail.com>
 * Copyright (C) 2008 Serge Humphrey <bob@bobtheblueberry.com>
 * 
 * This file is part of G-Creator.
 * G-Creator is free software and comes with ABSOLUTELY NO WARRANTY.
 * See LICENSE for more details.
 */
package org.gcreator.components.codeeditor;

import java.awt.Color;
import org.gcreator.components.codeeditor.KeywordList.Keyword;

public class GMLKeywordList extends KeywordList {
    private Color darkBlue = new Color(0x000080);
    private Keyword[] keywords = new Keyword[] {
new Keyword("argument_relative", darkBlue),
new Keyword("argument", darkBlue),
new Keyword("argument0", darkBlue),
new Keyword("argument1", darkBlue),
new Keyword("argument2", darkBlue),
new Keyword("argument3", darkBlue),
new Keyword("argument4", darkBlue),
new Keyword("argument5", darkBlue),
new Keyword("argument6", darkBlue),
new Keyword("argument7", darkBlue),
new Keyword("argument8", darkBlue),
new Keyword("argument9", darkBlue),
new Keyword("argument10", darkBlue),
new Keyword("argument11", darkBlue),
new Keyword("argument12", darkBlue),
new Keyword("argument13", darkBlue),
new Keyword("argument14", darkBlue),
new Keyword("argument15", darkBlue),
new Keyword("self", darkBlue),
new Keyword("other", darkBlue),
new Keyword("all", darkBlue),
new Keyword("noone", darkBlue),
new Keyword("global", darkBlue),
new Keyword("local", darkBlue),
new Keyword("true", darkBlue),
new Keyword("false", darkBlue),
new Keyword("pi", darkBlue),
new Keyword("is_real", darkBlue, true),
new Keyword("is_string", darkBlue, true),
new Keyword("random", darkBlue, true),
new Keyword("random_set_seed", darkBlue, true),
new Keyword("random_get_seed", darkBlue, true),
new Keyword("randomize", darkBlue, true),
new Keyword("choose", darkBlue, true),
new Keyword("abs", darkBlue, true),
new Keyword("round", darkBlue, true),
new Keyword("floor", darkBlue, true),
new Keyword("ceil", darkBlue, true),
new Keyword("sign", darkBlue, true),
new Keyword("frac", darkBlue, true),
new Keyword("sqrt", darkBlue, true),
new Keyword("sqr", darkBlue, true),
new Keyword("exp", darkBlue, true),
new Keyword("ln", darkBlue, true),
new Keyword("log2", darkBlue, true),
new Keyword("log10", darkBlue, true),
new Keyword("sin", darkBlue, true),
new Keyword("cos", darkBlue, true),
new Keyword("tan", darkBlue, true),
new Keyword("arcsin", darkBlue, true),
new Keyword("arccos", darkBlue, true),
new Keyword("arctan", darkBlue, true),
new Keyword("arctan2", darkBlue, true),
new Keyword("degtorad", darkBlue, true),
new Keyword("radtodeg", darkBlue, true),
new Keyword("power", darkBlue, true),
new Keyword("logn", darkBlue, true),
new Keyword("min", darkBlue, true),
new Keyword("max", darkBlue, true),
new Keyword("mean", darkBlue, true),
new Keyword("median", darkBlue, true),
new Keyword("point_distance", darkBlue, true),
new Keyword("point_direction", darkBlue, true),
new Keyword("lengthdir_x", darkBlue, true),
new Keyword("lengthdir_y", darkBlue, true),
new Keyword("real", darkBlue, true),
new Keyword("string", darkBlue, true),
new Keyword("string_format", darkBlue, true),
new Keyword("chr", darkBlue, true),
new Keyword("ord", darkBlue, true),
new Keyword("string_length", darkBlue, true),
new Keyword("string_pos", darkBlue, true),
new Keyword("string_copy", darkBlue, true),
new Keyword("string_char_at", darkBlue, true),
new Keyword("string_delete", darkBlue, true),
new Keyword("string_insert", darkBlue, true),
new Keyword("string_lower", darkBlue, true),
new Keyword("string_upper", darkBlue, true),
new Keyword("string_repeat", darkBlue, true),
new Keyword("string_letters", darkBlue, true),
new Keyword("string_digits", darkBlue, true),
new Keyword("string_lettersdigits", darkBlue, true),
new Keyword("string_replace", darkBlue, true),
new Keyword("string_replace_all", darkBlue, true),
new Keyword("string_count", darkBlue, true),
new Keyword("clipboard_has_text", darkBlue, true),
new Keyword("clipboard_set_text", darkBlue, true),
new Keyword("clipboard_get_text", darkBlue, true),
new Keyword("date_current_datetime", darkBlue, true),
new Keyword("date_current_date", darkBlue, true),
new Keyword("date_current_time", darkBlue, true),
new Keyword("date_create_datetime", darkBlue, true),
new Keyword("date_create_date", darkBlue, true),
new Keyword("date_create_time", darkBlue, true),
new Keyword("date_valid_datetime", darkBlue, true),
new Keyword("date_valid_date", darkBlue, true),
new Keyword("date_valid_time", darkBlue, true),
new Keyword("date_inc_year", darkBlue, true),
new Keyword("date_inc_month", darkBlue, true),
new Keyword("date_inc_week", darkBlue, true),
new Keyword("date_inc_day", darkBlue, true),
new Keyword("date_inc_hour", darkBlue, true),
new Keyword("date_inc_minute", darkBlue, true),
new Keyword("date_inc_second", darkBlue, true),
new Keyword("date_get_year", darkBlue, true),
new Keyword("date_get_month", darkBlue, true),
new Keyword("date_get_week", darkBlue, true),
new Keyword("date_get_day", darkBlue, true),
new Keyword("date_get_hour", darkBlue, true),
new Keyword("date_get_minute", darkBlue, true),
new Keyword("date_get_second", darkBlue, true),
new Keyword("date_get_weekday", darkBlue, true),
new Keyword("date_get_day_of_year", darkBlue, true),
new Keyword("date_get_hour_of_year", darkBlue, true),
new Keyword("date_get_minute_of_year", darkBlue, true),
new Keyword("date_get_second_of_year", darkBlue, true),
new Keyword("date_year_span", darkBlue, true),
new Keyword("date_month_span", darkBlue, true),
new Keyword("date_week_span", darkBlue, true),
new Keyword("date_day_span", darkBlue, true),
new Keyword("date_hour_span", darkBlue, true),
new Keyword("date_minute_span", darkBlue, true),
new Keyword("date_second_span", darkBlue, true),
new Keyword("date_compare_datetime", darkBlue, true),
new Keyword("date_compare_date", darkBlue, true),
new Keyword("date_compare_time", darkBlue, true),
new Keyword("date_date_of", darkBlue, true),
new Keyword("date_time_of", darkBlue, true),
new Keyword("date_datetime_string", darkBlue, true),
new Keyword("date_date_string", darkBlue, true),
new Keyword("date_time_string", darkBlue, true),
new Keyword("date_days_in_month", darkBlue, true),
new Keyword("date_days_in_year", darkBlue, true),
new Keyword("date_leap_year", darkBlue, true),
new Keyword("date_is_today", darkBlue, true),
new Keyword("x", darkBlue),
new Keyword("y", darkBlue),
new Keyword("xprevious", darkBlue),
new Keyword("yprevious", darkBlue),
new Keyword("xstart", darkBlue),
new Keyword("ystart", darkBlue),
new Keyword("hspeed", darkBlue),
new Keyword("vspeed", darkBlue),
new Keyword("direction", darkBlue),
new Keyword("speed", darkBlue),
new Keyword("friction", darkBlue),
new Keyword("gravity", darkBlue),
new Keyword("gravity_direction", darkBlue),
new Keyword("motion_set", darkBlue, true),
new Keyword("motion_add", darkBlue, true),
new Keyword("place_free", darkBlue, true),
new Keyword("place_empty", darkBlue, true),
new Keyword("place_meeting", darkBlue, true),
new Keyword("place_snapped", darkBlue, true),
new Keyword("move_random", darkBlue, true),
new Keyword("move_snap", darkBlue, true),
new Keyword("move_towards_point", darkBlue, true),
new Keyword("move_contact_solid", darkBlue, true),
new Keyword("move_contact_all", darkBlue, true),
new Keyword("move_outside_solid", darkBlue, true),
new Keyword("move_outside_all", darkBlue, true),
new Keyword("move_bounce_solid", darkBlue, true),
new Keyword("move_bounce_all", darkBlue, true),
new Keyword("move_wrap", darkBlue, true),
new Keyword("distance_to_point", darkBlue, true),
new Keyword("distance_to_object", darkBlue, true),
new Keyword("position_empty", darkBlue, true),
new Keyword("position_meeting", darkBlue, true),
new Keyword("path_start", darkBlue, true),
new Keyword("path_end", darkBlue, true),
new Keyword("path_index", darkBlue),
new Keyword("path_position", darkBlue),
new Keyword("path_positionprevious", darkBlue),
new Keyword("path_speed", darkBlue),
new Keyword("path_scale", darkBlue),
new Keyword("path_orientation", darkBlue),
new Keyword("path_endaction", darkBlue),
new Keyword("mp_linear_step", darkBlue, true),
new Keyword("mp_potential_step", darkBlue, true),
new Keyword("mp_linear_step_object", darkBlue, true),
new Keyword("mp_potential_step_object", darkBlue, true),
new Keyword("mp_potential_settings", darkBlue, true),
new Keyword("mp_linear_path", darkBlue, true),
new Keyword("mp_potential_path", darkBlue, true),
new Keyword("mp_linear_path_object", darkBlue, true),
new Keyword("mp_potential_path_object", darkBlue, true),
new Keyword("mp_grid_create", darkBlue, true),
new Keyword("mp_grid_destroy", darkBlue, true),
new Keyword("mp_grid_clear_all", darkBlue, true),
new Keyword("mp_grid_clear_cell", darkBlue, true),
new Keyword("mp_grid_clear_rectangle", darkBlue, true),
new Keyword("mp_grid_add_cell", darkBlue, true),
new Keyword("mp_grid_add_rectangle", darkBlue, true),
new Keyword("mp_grid_add_instances", darkBlue, true),
new Keyword("mp_grid_path", darkBlue, true),
new Keyword("mp_grid_draw", darkBlue, true),
new Keyword("collision_point", darkBlue, true),
new Keyword("collision_rectangle", darkBlue, true),
new Keyword("collision_circle", darkBlue, true),
new Keyword("collision_ellipse", darkBlue, true),
new Keyword("collision_line", darkBlue, true),
new Keyword("object_index", darkBlue),
new Keyword("id", darkBlue),
new Keyword("solid", darkBlue),
new Keyword("persistent", darkBlue),
new Keyword("mask_index", darkBlue),
new Keyword("instance_count", darkBlue),
new Keyword("instance_id", darkBlue),
new Keyword("instance_find", darkBlue, true),
new Keyword("instance_exists", darkBlue, true),
new Keyword("instance_number", darkBlue, true),
new Keyword("instance_position", darkBlue, true),
new Keyword("instance_nearest", darkBlue, true),
new Keyword("instance_furthest", darkBlue, true),
new Keyword("instance_place", darkBlue, true),
new Keyword("instance_create", darkBlue, true),
new Keyword("instance_copy", darkBlue, true),
new Keyword("instance_change", darkBlue, true),
new Keyword("instance_destroy", darkBlue, true),
new Keyword("position_destroy", darkBlue, true),
new Keyword("position_change", darkBlue, true),
new Keyword("instance_deactivate_all", darkBlue, true),
new Keyword("instance_deactivate_object", darkBlue, true),
new Keyword("instance_deactivate_region", darkBlue, true),
new Keyword("instance_activate_all", darkBlue, true),
new Keyword("instance_activate_object", darkBlue, true),
new Keyword("instance_activate_region", darkBlue, true),
new Keyword("room_speed", darkBlue),
new Keyword("fps", darkBlue),
new Keyword("current_time", darkBlue),
new Keyword("current_year", darkBlue),
new Keyword("current_month", darkBlue),
new Keyword("current_day", darkBlue),
new Keyword("current_weekday", darkBlue),
new Keyword("current_hour", darkBlue),
new Keyword("current_minute", darkBlue),
new Keyword("current_second", darkBlue),
new Keyword("sleep", darkBlue, true),
new Keyword("alarm[0..11]", darkBlue),
new Keyword("timeline_index", darkBlue),
new Keyword("timeline_position", darkBlue),
new Keyword("timeline_speed", darkBlue),
new Keyword("room", darkBlue),
new Keyword("room_first", darkBlue),
new Keyword("room_last", darkBlue),
new Keyword("room_width", darkBlue),
new Keyword("room_height", darkBlue),
new Keyword("room_caption", darkBlue),
new Keyword("room_persistent", darkBlue),
new Keyword("room_goto", darkBlue, true),
new Keyword("room_goto_previous", darkBlue, true),
new Keyword("room_goto_next", darkBlue, true),
new Keyword("room_previous", darkBlue, true),
new Keyword("room_next", darkBlue, true),
new Keyword("room_restart", darkBlue, true),
new Keyword("game_end", darkBlue, true),
new Keyword("game_restart", darkBlue, true),
new Keyword("game_load", darkBlue, true),
new Keyword("game_save", darkBlue, true),

new Keyword("transition_kind", darkBlue),
new Keyword("transition_steps", darkBlue),
new Keyword("transition_color", darkBlue),
new Keyword("transition_define", darkBlue, true),
new Keyword("transition_exists", darkBlue, true),
new Keyword("score", darkBlue),
new Keyword("lives", darkBlue),
new Keyword("health", darkBlue),
new Keyword("show_score", darkBlue),
new Keyword("show_lives", darkBlue),
new Keyword("show_health", darkBlue),
new Keyword("caption_score", darkBlue),
new Keyword("caption_lives", darkBlue),
new Keyword("caption_health", darkBlue),
new Keyword("event_perform", darkBlue, true),
new Keyword("event_user", darkBlue, true),
new Keyword("event_perform_object", darkBlue, true),
new Keyword("event_inherited", darkBlue, true),
new Keyword("event_type", darkBlue),
new Keyword("event_number", darkBlue),
new Keyword("event_object", darkBlue),
new Keyword("event_action", darkBlue),
new Keyword("ev_create", darkBlue),
new Keyword("ev_destroy", darkBlue),
new Keyword("ev_step", darkBlue),
new Keyword("ev_alarm", darkBlue),
new Keyword("ev_keyboard", darkBlue),
new Keyword("ev_mouse", darkBlue),
new Keyword("ev_collision", darkBlue),
new Keyword("ev_other", darkBlue),
new Keyword("ev_draw", darkBlue),
new Keyword("ev_keypress", darkBlue),
new Keyword("ev_keyrelease", darkBlue),
new Keyword("ev_left_button", darkBlue),
new Keyword("ev_right_button", darkBlue),
new Keyword("ev_middle_button", darkBlue),
new Keyword("ev_no_button", darkBlue),
new Keyword("ev_left_press", darkBlue),
new Keyword("ev_right_press", darkBlue),
new Keyword("ev_middle_press", darkBlue),
new Keyword("ev_left_release", darkBlue),
new Keyword("ev_right_release", darkBlue),
new Keyword("ev_middle_release", darkBlue),
new Keyword("ev_mouse_enter", darkBlue),
new Keyword("ev_mouse_leave", darkBlue),
new Keyword("ev_mouse_wheel_up", darkBlue),
new Keyword("ev_mouse_wheel_down", darkBlue),
new Keyword("ev_global_left_button", darkBlue),
new Keyword("ev_global_right_button", darkBlue),
new Keyword("ev_global_middle_button", darkBlue),
new Keyword("ev_global_left_press", darkBlue),
new Keyword("ev_global_right_press", darkBlue),
new Keyword("ev_global_middle_press", darkBlue),
new Keyword("ev_global_left_release", darkBlue),
new Keyword("ev_global_right_release", darkBlue),
new Keyword("ev_global_middle_release", darkBlue),
new Keyword("ev_joystick1_left", darkBlue),
new Keyword("ev_joystick1_right", darkBlue),
new Keyword("ev_joystick1_up", darkBlue),
new Keyword("ev_joystick1_down", darkBlue),
new Keyword("ev_joystick1_button1", darkBlue),
new Keyword("ev_joystick1_button2", darkBlue),
new Keyword("ev_joystick1_button3", darkBlue),
new Keyword("ev_joystick1_button4", darkBlue),
new Keyword("ev_joystick1_button5", darkBlue),
new Keyword("ev_joystick1_button6", darkBlue),
new Keyword("ev_joystick1_button7", darkBlue),
new Keyword("ev_joystick1_button8", darkBlue),
new Keyword("ev_joystick2_left", darkBlue),
new Keyword("ev_joystick2_right", darkBlue),
new Keyword("ev_joystick2_up", darkBlue),
new Keyword("ev_joystick2_down", darkBlue),
new Keyword("ev_joystick2_button1", darkBlue),
new Keyword("ev_joystick2_button2", darkBlue),
new Keyword("ev_joystick2_button3", darkBlue),
new Keyword("ev_joystick2_button4", darkBlue),
new Keyword("ev_joystick2_button5", darkBlue),
new Keyword("ev_joystick2_button6", darkBlue),
new Keyword("ev_joystick2_button7", darkBlue),
new Keyword("ev_joystick2_button8", darkBlue),
new Keyword("ev_outside", darkBlue),
new Keyword("ev_boundary", darkBlue),
new Keyword("ev_game_start", darkBlue),
new Keyword("ev_game_end", darkBlue),
new Keyword("ev_room_start", darkBlue),
new Keyword("ev_room_end", darkBlue),
new Keyword("ev_no_more_lives", darkBlue),
new Keyword("ev_animation_end", darkBlue),
new Keyword("ev_end_of_path", darkBlue),
new Keyword("ev_no_more_health", darkBlue),
new Keyword("ev_close_button", darkBlue),
new Keyword("ev_user0", darkBlue),
new Keyword("ev_user1", darkBlue),
new Keyword("ev_user2", darkBlue),
new Keyword("ev_user3", darkBlue),
new Keyword("ev_user4", darkBlue),
new Keyword("ev_user5", darkBlue),
new Keyword("ev_user6", darkBlue),
new Keyword("ev_user7", darkBlue),
new Keyword("ev_user8", darkBlue),
new Keyword("ev_user9", darkBlue),
new Keyword("ev_user10", darkBlue),
new Keyword("ev_user11", darkBlue),
new Keyword("ev_user12", darkBlue),
new Keyword("ev_user13", darkBlue),
new Keyword("ev_user14", darkBlue),
new Keyword("ev_user15", darkBlue),
new Keyword("ev_step_normal", darkBlue),
new Keyword("ev_step_begin", darkBlue),
new Keyword("ev_step_end", darkBlue),
new Keyword("error_occurred", darkBlue),
new Keyword("error_last", darkBlue),
new Keyword("show_debug_message", darkBlue, true),
new Keyword("variable_global_exists", darkBlue, true),
new Keyword("variable_global_get", darkBlue, true),
new Keyword("variable_global_array_get", darkBlue, true),
new Keyword("variable_global_array2_get", darkBlue, true),
new Keyword("variable_global_set", darkBlue, true),
new Keyword("variable_global_array_set", darkBlue, true),
new Keyword("variable_global_array2_set", darkBlue, true),
new Keyword("variable_local_exists", darkBlue, true),
new Keyword("variable_local_get", darkBlue, true),
new Keyword("variable_local_array_get", darkBlue, true),
new Keyword("variable_local_array2_get", darkBlue, true),
new Keyword("variable_local_set", darkBlue, true),
new Keyword("variable_local_array_set", darkBlue, true),
new Keyword("variable_local_array2_set", darkBlue, true),
new Keyword("set_program_priority", darkBlue, true),
new Keyword("keyboard_key", darkBlue),
new Keyword("keyboard_lastkey", darkBlue),
new Keyword("keyboard_lastchar", darkBlue),
new Keyword("keyboard_string", darkBlue),
new Keyword("keyboard_set_map", darkBlue, true),
new Keyword("keyboard_get_map", darkBlue, true),
new Keyword("keyboard_unset_map", darkBlue, true),
new Keyword("keyboard_check", darkBlue, true),
new Keyword("keyboard_check_pressed", darkBlue, true),
new Keyword("keyboard_check_released", darkBlue, true),
new Keyword("keyboard_check_direct", darkBlue, true),
new Keyword("keyboard_get_numlock", darkBlue, true),
new Keyword("keyboard_set_numlock", darkBlue, true),
new Keyword("keyboard_key_press", darkBlue, true),
new Keyword("keyboard_key_release", darkBlue, true),
new Keyword("vk_nokey", darkBlue),
new Keyword("vk_anykey", darkBlue),
new Keyword("vk_enter", darkBlue),
new Keyword("vk_return", darkBlue),
new Keyword("vk_shift", darkBlue),
new Keyword("vk_control", darkBlue),
new Keyword("vk_alt", darkBlue),
new Keyword("vk_escape", darkBlue),
new Keyword("vk_space", darkBlue),
new Keyword("vk_backspace", darkBlue),
new Keyword("vk_tab", darkBlue),
new Keyword("vk_pause", darkBlue),
new Keyword("vk_printscreen", darkBlue),
new Keyword("vk_left", darkBlue),
new Keyword("vk_right", darkBlue),
new Keyword("vk_up", darkBlue),
new Keyword("vk_down", darkBlue),
new Keyword("vk_home", darkBlue),
new Keyword("vk_end", darkBlue),
new Keyword("vk_delete", darkBlue),
new Keyword("vk_insert", darkBlue),
new Keyword("vk_pageup", darkBlue),
new Keyword("vk_pagedown", darkBlue),
new Keyword("vk_f1", darkBlue),
new Keyword("vk_f2", darkBlue),
new Keyword("vk_f3", darkBlue),
new Keyword("vk_f4", darkBlue),
new Keyword("vk_f5", darkBlue),
new Keyword("vk_f6", darkBlue),
new Keyword("vk_f7", darkBlue),
new Keyword("vk_f8", darkBlue),
new Keyword("vk_f9", darkBlue),
new Keyword("vk_f10", darkBlue),
new Keyword("vk_f11", darkBlue),
new Keyword("vk_f12", darkBlue),
new Keyword("vk_numpad0", darkBlue),
new Keyword("vk_numpad1", darkBlue),
new Keyword("vk_numpad2", darkBlue),
new Keyword("vk_numpad3", darkBlue),
new Keyword("vk_numpad4", darkBlue),
new Keyword("vk_numpad5", darkBlue),
new Keyword("vk_numpad6", darkBlue),
new Keyword("vk_numpad7", darkBlue),
new Keyword("vk_numpad8", darkBlue),
new Keyword("vk_numpad9", darkBlue),
new Keyword("vk_divide", darkBlue),
new Keyword("vk_multiply", darkBlue),
new Keyword("vk_subtract", darkBlue),
new Keyword("vk_add", darkBlue),
new Keyword("vk_decimal", darkBlue),
new Keyword("vk_lshift", darkBlue),
new Keyword("vk_lcontrol", darkBlue),
new Keyword("vk_lalt", darkBlue),
new Keyword("vk_rshift", darkBlue),
new Keyword("vk_rcontrol", darkBlue),
new Keyword("vk_ralt", darkBlue),
new Keyword("keyboard_clear", darkBlue, true),
new Keyword("io_clear", darkBlue, true),
new Keyword("io_handle", darkBlue, true),
new Keyword("keyboard_wait", darkBlue, true),
new Keyword("mouse_x", darkBlue),
new Keyword("mouse_y", darkBlue),
new Keyword("mouse_button", darkBlue),
new Keyword("mouse_lastbutton", darkBlue),
new Keyword("mb_any", darkBlue),
new Keyword("mb_none", darkBlue),
new Keyword("mb_left", darkBlue),
new Keyword("mb_right", darkBlue),
new Keyword("mb_middle", darkBlue),
new Keyword("mouse_check_button", darkBlue, true),
new Keyword("mouse_check_button_pressed", darkBlue, true),
new Keyword("mouse_check_button_released", darkBlue, true),
new Keyword("mouse_clear", darkBlue, true),
new Keyword("mouse_wait", darkBlue, true),
new Keyword("cursor_sprite", darkBlue),
new Keyword("joystick_exists", darkBlue, true),
new Keyword("joystick_direction", darkBlue, true),
new Keyword("joystick_name", darkBlue, true),
new Keyword("joystick_axes", darkBlue, true),
new Keyword("joystick_buttons", darkBlue, true),
new Keyword("joystick_has_pov", darkBlue, true),
new Keyword("joystick_check_button", darkBlue, true),
new Keyword("joystick_xpos", darkBlue, true),
new Keyword("joystick_ypos", darkBlue, true),
new Keyword("joystick_zpos", darkBlue, true),
new Keyword("joystick_rpos", darkBlue, true),
new Keyword("joystick_upos", darkBlue, true),
new Keyword("joystick_vpos", darkBlue, true),
new Keyword("joystick_pov", darkBlue, true),
new Keyword("visible ", darkBlue),
new Keyword("sprite_index ", darkBlue),
new Keyword("sprite_width ", darkBlue),
new Keyword("sprite_height ", darkBlue),
new Keyword("sprite_xoffset ", darkBlue),
new Keyword("sprite_yoffset ", darkBlue),
new Keyword("image_number ", darkBlue),
new Keyword("image_index ", darkBlue),
new Keyword("image_speed ", darkBlue),
new Keyword("depth ", darkBlue),
new Keyword("image_xscale ", darkBlue),
new Keyword("image_yscale ", darkBlue),
new Keyword("image_angle ", darkBlue),
new Keyword("image_alpha ", darkBlue),
new Keyword("image_blend ", darkBlue),
new Keyword("bbox_left ", darkBlue),
new Keyword("bbox_right ", darkBlue),
new Keyword("bbox_top ", darkBlue),
new Keyword("bbox_bottom", darkBlue),
new Keyword("background_color ", darkBlue),
new Keyword("background_showcolor ", darkBlue),
new Keyword("background_visible[0..7] ", darkBlue),
new Keyword("background_foreground[0..7] ", darkBlue),
new Keyword("background_index[0..7] ", darkBlue),
new Keyword("background_x[0..7] ", darkBlue),
new Keyword("background_y[0...7] ", darkBlue),
new Keyword("background_width[0...7] ", darkBlue),
new Keyword("background_height[0...7] ", darkBlue),
new Keyword("background_htiled[0..7] ", darkBlue),
new Keyword("background_vtiled[0..7] ", darkBlue),
new Keyword("background_xscale[0..7] ", darkBlue),
new Keyword("background_yscale[0..7] ", darkBlue),
new Keyword("background_hspeed[0..7] ", darkBlue),
new Keyword("background_vspeed[0..7] ", darkBlue),
new Keyword("background_blend[0..7] ", darkBlue),
new Keyword("background_alpha[0..7]", darkBlue),
new Keyword("draw_sprite", darkBlue, true),
new Keyword("draw_sprite_ext", darkBlue, true),
new Keyword("draw_sprite_stretched", darkBlue, true),
new Keyword("draw_sprite_stretched_ext", darkBlue, true),
new Keyword("draw_sprite_tiled", darkBlue, true),
new Keyword("draw_sprite_tiled_ext", darkBlue, true),
new Keyword("draw_sprite_part", darkBlue, true),
new Keyword("draw_sprite_part_ext", darkBlue, true),
new Keyword("draw_sprite_general", darkBlue, true),
new Keyword("draw_background", darkBlue, true),
new Keyword("draw_background_ext", darkBlue, true),
new Keyword("draw_background_stretched", darkBlue, true),
new Keyword("draw_background_stretched_ext", darkBlue, true),
new Keyword("draw_background_tiled", darkBlue, true),
new Keyword("draw_background_tiled_ext", darkBlue, true),
new Keyword("draw_background_part", darkBlue, true),
new Keyword("draw_background_part_ext", darkBlue, true),
new Keyword("draw_background_general", darkBlue, true),
new Keyword("draw_clear", darkBlue, true),
new Keyword("draw_clear_alpha", darkBlue, true),
new Keyword("draw_point", darkBlue, true),
new Keyword("draw_line", darkBlue, true),
new Keyword("draw_line_width", darkBlue, true),
new Keyword("draw_rectangle", darkBlue, true),
new Keyword("draw_roundrect", darkBlue, true),
new Keyword("draw_triangle", darkBlue, true),
new Keyword("draw_circle", darkBlue, true),
new Keyword("draw_ellipse", darkBlue, true),
new Keyword("draw_set_circle_precision", darkBlue, true),
new Keyword("draw_arrow", darkBlue, true),
new Keyword("draw_button", darkBlue, true),
new Keyword("draw_path", darkBlue, true),
new Keyword("draw_healthbar", darkBlue, true),
new Keyword("draw_getpixel", darkBlue, true),
new Keyword("draw_set_color", darkBlue, true),
new Keyword("draw_set_alpha", darkBlue, true),
new Keyword("draw_get_color", darkBlue, true),
new Keyword("draw_get_alpha", darkBlue, true),
new Keyword("c_aqua", darkBlue),
new Keyword("c_black", darkBlue),
new Keyword("c_blue", darkBlue),
new Keyword("c_dkgray", darkBlue),
new Keyword("c_fuchsia", darkBlue),
new Keyword("c_gray", darkBlue),
new Keyword("c_green", darkBlue),
new Keyword("c_lime", darkBlue),
new Keyword("c_ltgray", darkBlue),
new Keyword("c_maroon", darkBlue),
new Keyword("c_navy", darkBlue),
new Keyword("c_olive", darkBlue),
new Keyword("c_purple", darkBlue),
new Keyword("c_red", darkBlue),
new Keyword("c_silver", darkBlue),
new Keyword("c_teal", darkBlue),
new Keyword("c_white", darkBlue),
new Keyword("c_yellow", darkBlue),
new Keyword("c_orange", darkBlue),
new Keyword("make_color_rgb", darkBlue, true),
new Keyword("make_color_hsv", darkBlue, true),
new Keyword("color_get_red", darkBlue, true),
new Keyword("color_get_green", darkBlue, true),
new Keyword("color_get_blue", darkBlue, true),
new Keyword("color_get_hue", darkBlue, true),
new Keyword("color_get_saturation", darkBlue, true),
new Keyword("color_get_value", darkBlue, true),
new Keyword("merge_color", darkBlue, true),
new Keyword("screen_save", darkBlue, true),
new Keyword("screen_save_part", darkBlue, true),
new Keyword("draw_set_font", darkBlue, true),
new Keyword("draw_set_halign", darkBlue, true),
new Keyword("fa_left", darkBlue),
new Keyword("fa_center", darkBlue),
new Keyword("fa_right", darkBlue),
new Keyword("draw_set_valign", darkBlue, true),
new Keyword("fa_top", darkBlue),
new Keyword("fa_middle", darkBlue),
new Keyword("fa_bottom", darkBlue),
new Keyword("draw_text", darkBlue, true),
new Keyword("draw_text_ext", darkBlue, true),
new Keyword("string_width", darkBlue, true),
new Keyword("string_height", darkBlue, true),
new Keyword("string_width_ext", darkBlue, true),
new Keyword("string_height_ext", darkBlue, true),
new Keyword("draw_text_transformed", darkBlue, true),
new Keyword("draw_text_ext_transformed", darkBlue, true),
new Keyword("draw_text_color", darkBlue, true),
new Keyword("draw_text_ext_color", darkBlue, true),
new Keyword("draw_text_transformed_color", darkBlue, true),
new Keyword("draw_text_ext_transformed_color", darkBlue, true),
new Keyword("draw_point_color", darkBlue, true),
new Keyword("draw_line_color", darkBlue, true),
new Keyword("draw_line_width_color", darkBlue, true),
new Keyword("draw_rectangle_color", darkBlue, true),
new Keyword("draw_roundrect_color", darkBlue, true),
new Keyword("draw_triangle_color", darkBlue, true),
new Keyword("draw_circle_color", darkBlue, true),
new Keyword("draw_ellipse_color", darkBlue, true),
new Keyword("pr_pointlist", darkBlue),
new Keyword("pr_linelist", darkBlue),
new Keyword("pr_linestrip", darkBlue),
new Keyword("pr_trianglelist", darkBlue),
new Keyword("pr_trianglestrip", darkBlue),
new Keyword("pr_trianglefan", darkBlue),
new Keyword("draw_primitive_begin", darkBlue, true),
new Keyword("draw_vertex", darkBlue, true),
new Keyword("draw_vertex_color", darkBlue, true),
new Keyword("draw_primitive_end", darkBlue, true),
new Keyword("sprite_get_texture", darkBlue, true),
new Keyword("background_get_texture", darkBlue, true),
new Keyword("texture_preload", darkBlue, true),
new Keyword("texture_set_priority", darkBlue, true),
new Keyword("texture_get_width", darkBlue, true),
new Keyword("texture_get_height", darkBlue, true),
new Keyword("draw_primitive_begin_texture", darkBlue, true),
new Keyword("draw_vertex_texture", darkBlue, true),
new Keyword("draw_vertex_texture_color", darkBlue, true),
new Keyword("texture_set_interpolation", darkBlue, true),
new Keyword("texture_set_blending", darkBlue, true),
new Keyword("texture_set_repeat", darkBlue, true),
new Keyword("draw_set_blend_mode", darkBlue, true),
new Keyword("draw_set_blend_mode_ext", darkBlue, true),
new Keyword("bm_normal", darkBlue),
new Keyword("bm_add", darkBlue),
new Keyword("bm_max", darkBlue),
new Keyword("bm_subtract", darkBlue),
new Keyword("bm_zero", darkBlue),
new Keyword("bm_one", darkBlue),
new Keyword("bm_src_color", darkBlue),
new Keyword("bm_inv_src_color", darkBlue),
new Keyword("bm_src_alpha", darkBlue),
new Keyword("bm_inv_src_alpha", darkBlue),
new Keyword("bm_dest_alpha", darkBlue),
new Keyword("bm_inv_dest_alpha", darkBlue),
new Keyword("bm_dest_color", darkBlue),
new Keyword("bm_inv_dest_color", darkBlue),
new Keyword("bm_src_alpha_sat", darkBlue),
new Keyword("surface_create", darkBlue, true),
new Keyword("surface_free", darkBlue, true),
new Keyword("surface_exists", darkBlue, true),
new Keyword("surface_get_width", darkBlue, true),
new Keyword("surface_get_height", darkBlue, true),
new Keyword("surface_get_texture", darkBlue, true),
new Keyword("surface_set_target", darkBlue, true),
new Keyword("surface_reset_target", darkBlue, true),
new Keyword("draw_surface", darkBlue, true),
new Keyword("draw_surface_stretched", darkBlue, true),
new Keyword("draw_surface_tiled", darkBlue, true),
new Keyword("draw_surface_part", darkBlue, true),
new Keyword("draw_surface_ext", darkBlue, true),
new Keyword("draw_surface_stretched_ext", darkBlue, true),
new Keyword("draw_surface_tiled_ext", darkBlue, true),
new Keyword("draw_surface_part_ext", darkBlue, true),
new Keyword("draw_surface_general", darkBlue, true),
new Keyword("surface_getpixel", darkBlue, true),
new Keyword("surface_save", darkBlue, true),
new Keyword("surface_save_part", darkBlue, true),
new Keyword("surface_copy", darkBlue, true),
new Keyword("surface_copy_part", darkBlue, true),
new Keyword("tile_add", darkBlue, true),
new Keyword("tile_delete", darkBlue, true),
new Keyword("tile_exists", darkBlue, true),
new Keyword("tile_get_x", darkBlue, true),
new Keyword("tile_get_y", darkBlue, true),
new Keyword("tile_get_left", darkBlue, true),
new Keyword("tile_get_top", darkBlue, true),
new Keyword("tile_get_width", darkBlue, true),
new Keyword("tile_get_height", darkBlue, true),
new Keyword("tile_get_depth", darkBlue, true),
new Keyword("tile_get_visible", darkBlue, true),
new Keyword("tile_get_xscale", darkBlue, true),
new Keyword("tile_get_yscale", darkBlue, true),
new Keyword("tile_get_background", darkBlue, true),
new Keyword("tile_get_blend", darkBlue, true),
new Keyword("tile_get_alpha", darkBlue, true),
new Keyword("tile_set_position", darkBlue, true),
new Keyword("tile_set_region", darkBlue, true),
new Keyword("tile_set_background", darkBlue, true),
new Keyword("tile_set_visible", darkBlue, true),
new Keyword("tile_set_depth", darkBlue, true),
new Keyword("tile_set_scale", darkBlue, true),
new Keyword("tile_set_blend", darkBlue, true),
new Keyword("tile_set_alpha", darkBlue, true),
new Keyword("tile_layer_hide", darkBlue, true),
new Keyword("tile_layer_show", darkBlue, true),
new Keyword("tile_layer_delete", darkBlue, true),
new Keyword("tile_layer_shift", darkBlue, true),
new Keyword("tile_layer_find", darkBlue, true),
new Keyword("tile_layer_delete_at", darkBlue, true),
new Keyword("tile_layer_depth", darkBlue, true),
new Keyword("display_get_width", darkBlue, true),
new Keyword("display_get_height", darkBlue, true),
new Keyword("display_get_colordepth", darkBlue, true),
new Keyword("display_get_frequency", darkBlue, true),
new Keyword("display_set_size", darkBlue, true),
new Keyword("display_set_colordepth", darkBlue, true),
new Keyword("display_set_frequency", darkBlue, true),
new Keyword("display_set_all", darkBlue, true),
new Keyword("display_test_all", darkBlue, true),
new Keyword("display_reset", darkBlue, true),
new Keyword("display_mouse_get_x", darkBlue, true),
new Keyword("display_mouse_get_y", darkBlue, true),
new Keyword("display_mouse_set", darkBlue, true),
new Keyword("window_set_visible", darkBlue, true),
new Keyword("window_get_visible", darkBlue, true),
new Keyword("window_set_fullscreen", darkBlue, true),
new Keyword("window_get_fullscreen", darkBlue, true),
new Keyword("window_set_showborder", darkBlue, true),
new Keyword("window_get_showborder", darkBlue, true),
new Keyword("window_set_showicons", darkBlue, true),
new Keyword("window_get_showicons", darkBlue, true),
new Keyword("window_set_stayontop", darkBlue, true),
new Keyword("window_get_stayontop", darkBlue, true),
new Keyword("window_set_sizeable", darkBlue, true),
new Keyword("window_get_sizeable", darkBlue, true),
new Keyword("window_set_caption", darkBlue, true),
new Keyword("window_get_caption", darkBlue, true),
new Keyword("window_set_cursor", darkBlue, true),
new Keyword("cr_default", darkBlue),
new Keyword("cr_none", darkBlue),
new Keyword("cr_arrrow", darkBlue),
new Keyword("cr_cross", darkBlue),
new Keyword("cr_beam", darkBlue),
new Keyword("cr_size_nesw", darkBlue),
new Keyword("cr_size_ns", darkBlue),
new Keyword("cr_size_nwse", darkBlue),
new Keyword("cr_size_we", darkBlue),
new Keyword("cr_uparrow", darkBlue),
new Keyword("cr_hourglass", darkBlue),
new Keyword("cr_drag", darkBlue),
new Keyword("cr_nodrop", darkBlue),
new Keyword("cr_hsplit", darkBlue),
new Keyword("cr_vsplit", darkBlue),
new Keyword("cr_multidrag", darkBlue),
new Keyword("cr_sqlwait", darkBlue),
new Keyword("cr_no", darkBlue),
new Keyword("cr_appstart", darkBlue),
new Keyword("cr_help", darkBlue),
new Keyword("cr_handpoint", darkBlue),
new Keyword("cr_size_all", darkBlue),
new Keyword("window_get_cursor", darkBlue, true),
new Keyword("window_set_color", darkBlue, true),
new Keyword("window_get_color", darkBlue, true),
new Keyword("window_set_region_scale", darkBlue, true),
new Keyword("window_get_region_scale", darkBlue, true),
new Keyword("window_set_position", darkBlue, true),
new Keyword("window_set_size", darkBlue, true),
new Keyword("window_set_rectangle", darkBlue, true),
new Keyword("window_center", darkBlue, true),
new Keyword("window_default", darkBlue, true),
new Keyword("window_get_x", darkBlue, true),
new Keyword("window_get_y", darkBlue, true),
new Keyword("window_get_width", darkBlue, true),
new Keyword("window_get_height", darkBlue, true),
new Keyword("window_mouse_get_x", darkBlue, true),
new Keyword("window_mouse_get_y", darkBlue, true),
new Keyword("window_mouse_set", darkBlue, true),
new Keyword("view_enabled", darkBlue),
new Keyword("view_current", darkBlue),
new Keyword("view_visible[0..7]", darkBlue),
new Keyword("view_xview[0..7]", darkBlue),
new Keyword("view_yview[0..7]", darkBlue),
new Keyword("view_wview[0..7]", darkBlue),
new Keyword("view_hview[0..7]", darkBlue),
new Keyword("view_xport[0..7]", darkBlue),
new Keyword("view_yport[0..7]", darkBlue),
new Keyword("view_wport[0..7]", darkBlue),
new Keyword("view_hport[0..7]", darkBlue),
new Keyword("view_angle[0..7]", darkBlue),
new Keyword("view_hborder[0..7]", darkBlue),
new Keyword("view_vborder[0..7]", darkBlue),
new Keyword("view_hspeed[0..7]", darkBlue),
new Keyword("view_vspeed[0..7]", darkBlue),
new Keyword("view_object[0..7]", darkBlue),
new Keyword("window_set_region_size", darkBlue, true),
new Keyword("window_get_region_width", darkBlue, true),
new Keyword("window_get_region_height", darkBlue, true),
new Keyword("window_view_mouse_get_x", darkBlue, true),
new Keyword("window_view_mouse_get_y", darkBlue, true),
new Keyword("window_view_mouse_set", darkBlue, true),
new Keyword("window_views_mouse_get_x", darkBlue, true),
new Keyword("window_views_mouse_get_y", darkBlue, true),
new Keyword("window_views_mouse_set", darkBlue, true),
new Keyword("screen_redraw", darkBlue, true),
new Keyword("screen_refresh", darkBlue, true),
new Keyword("screen_wait_vsync", darkBlue, true),
new Keyword("set_automatic_draw", darkBlue, true),
new Keyword("set_synchronization", darkBlue, true),
new Keyword("sound_play", darkBlue, true),
new Keyword("sound_loop", darkBlue, true),
new Keyword("sound_stop", darkBlue, true),
new Keyword("sound_stop_all", darkBlue, true),
new Keyword("sound_isplaying", darkBlue, true),
new Keyword("sound_volume", darkBlue, true),
new Keyword("sound_global_volume", darkBlue, true),
new Keyword("sound_fade", darkBlue, true),
new Keyword("sound_pan", darkBlue, true),
new Keyword("sound_background_tempo", darkBlue, true),
new Keyword("sound_set_search_directory", darkBlue, true),
new Keyword("se_none", darkBlue),
new Keyword("se_chorus", darkBlue),
new Keyword("se_echo", darkBlue),
new Keyword("se_flanger", darkBlue),
new Keyword("se_gargle", darkBlue),
new Keyword("se_reverb", darkBlue),
new Keyword("se_compressor", darkBlue),
new Keyword("se_equalizer", darkBlue),
new Keyword("sound_effect_set", darkBlue, true),
new Keyword("sound_effect_chorus", darkBlue, true),
new Keyword("sound_effect_echo", darkBlue, true),
new Keyword("sound_effect_flanger", darkBlue, true),
new Keyword("sound_effect_gargle", darkBlue, true),
new Keyword("sound_effect_reverb", darkBlue, true),
new Keyword("sound_effect_compressor", darkBlue, true),
new Keyword("sound_effect_equalizer", darkBlue, true),
new Keyword("sound_3d_set_sound_position", darkBlue, true),
new Keyword("sound_3d_set_sound_velocity", darkBlue, true),
new Keyword("sound_3d_set_sound_distance", darkBlue, true),
new Keyword("sound_3d_set_sound_cone", darkBlue, true),
new Keyword("cd_init", darkBlue, true),
new Keyword("cd_present", darkBlue, true),
new Keyword("cd_number", darkBlue, true),
new Keyword("cd_playing", darkBlue, true),
new Keyword("cd_paused", darkBlue, true),
new Keyword("cd_track", darkBlue, true),
new Keyword("cd_length", darkBlue, true),
new Keyword("cd_track_length", darkBlue, true),
new Keyword("cd_position", darkBlue, true),
new Keyword("cd_track_position", darkBlue, true),
new Keyword("cd_play", darkBlue, true),
new Keyword("cd_stop", darkBlue, true),
new Keyword("cd_pause", darkBlue, true),
new Keyword("cd_resume", darkBlue, true),
new Keyword("cd_set_position", darkBlue, true),
new Keyword("cd_set_track_position", darkBlue, true),
new Keyword("cd_open_door", darkBlue, true),
new Keyword("cd_close_door", darkBlue, true),
new Keyword("MCI_command", darkBlue, true),
new Keyword("splash_show_video", darkBlue, true),
new Keyword("splash_show_text", darkBlue, true),
new Keyword("splash_show_image", darkBlue, true),
new Keyword("splash_set_caption", darkBlue, true),
new Keyword("splash_set_fullscreen", darkBlue, true),
new Keyword("splash_set_border", darkBlue, true),
new Keyword("splash_set_size", darkBlue, true),
new Keyword("splash_set_adapt", darkBlue, true),
new Keyword("splash_set_top", darkBlue, true),
new Keyword("splash_set_color", darkBlue, true),
new Keyword("splash_set_main", darkBlue, true),
new Keyword("splash_set_scale", darkBlue, true),
new Keyword("splash_set_cursor", darkBlue, true),
new Keyword("splash_set_interrupt", darkBlue, true),
new Keyword("splash_set_stop_key", darkBlue, true),
new Keyword("splash_set_stop_mouse", darkBlue, true),
new Keyword("show_info", darkBlue, true),
new Keyword("load_info", darkBlue, true),
new Keyword("show_message", darkBlue, true),
new Keyword("show_message_ext", darkBlue, true),
new Keyword("show_question", darkBlue, true),
new Keyword("get_integer", darkBlue, true),
new Keyword("get_string", darkBlue, true),
new Keyword("message_background", darkBlue, true),
new Keyword("message_button", darkBlue, true),
new Keyword("message_alpha", darkBlue, true),
new Keyword("message_text_font", darkBlue, true),
new Keyword("message_button_font", darkBlue, true),
new Keyword("message_input_font", darkBlue, true),
new Keyword("message_mouse_color", darkBlue, true),
new Keyword("message_input_color", darkBlue, true),
new Keyword("message_position", darkBlue, true),
new Keyword("message_size", darkBlue, true),
new Keyword("message_caption", darkBlue, true),
new Keyword("show_menu", darkBlue, true),
new Keyword("show_menu_pos", darkBlue, true),
new Keyword("get_color", darkBlue, true),
new Keyword("get_open_filename", darkBlue, true),
new Keyword("get_save_filename", darkBlue, true),
new Keyword("get_directory", darkBlue, true),
new Keyword("get_directory_alt", darkBlue, true),
new Keyword("show_error", darkBlue, true),
new Keyword("highscore_show_ext", darkBlue, true),
new Keyword("highscore_show", darkBlue, true),
new Keyword("highscore_set_background", darkBlue, true),
new Keyword("highscore_set_border", darkBlue, true),
new Keyword("highscore_set_font", darkBlue, true),
new Keyword("highscore_set_strings", darkBlue, true),
new Keyword("highscore_set_colors", darkBlue, true),
new Keyword("highscore_clear", darkBlue, true),
new Keyword("highscore_add", darkBlue, true),
new Keyword("highscore_add_current", darkBlue, true),
new Keyword("highscore_value", darkBlue, true),
new Keyword("highscore_name", darkBlue, true),
new Keyword("draw_highscore", darkBlue, true),
new Keyword("sprite_exists", darkBlue, true),
new Keyword("sprite_get_name", darkBlue, true),
new Keyword("sprite_get_number", darkBlue, true),
new Keyword("sprite_get_width", darkBlue, true),
new Keyword("sprite_get_height", darkBlue, true),
new Keyword("sprite_get_transparent", darkBlue, true),
new Keyword("sprite_get_smooth", darkBlue, true),
new Keyword("sprite_get_preload", darkBlue, true),
new Keyword("sprite_get_xoffset", darkBlue, true),
new Keyword("sprite_get_yoffset", darkBlue, true),
new Keyword("sprite_get_bbox_mode", darkBlue, true),
new Keyword("sprite_get_bbox_left", darkBlue, true),
new Keyword("sprite_get_bbox_right", darkBlue, true),
new Keyword("sprite_get_bbox_top", darkBlue, true),
new Keyword("sprite_get_bbox_bottom", darkBlue, true),
new Keyword("sprite_get_precise", darkBlue, true),
new Keyword("sprite_save", darkBlue, true),
new Keyword("sound_exists", darkBlue, true),
new Keyword("sound_get_name", darkBlue, true),
new Keyword("sound_get_kind", darkBlue, true),
new Keyword("sound_get_preload", darkBlue, true),
new Keyword("sound_discard", darkBlue, true),
new Keyword("sound_restore", darkBlue, true),
new Keyword("background_exists", darkBlue, true),
new Keyword("background_get_name", darkBlue, true),
new Keyword("background_get_width", darkBlue, true),
new Keyword("background_get_height", darkBlue, true),
new Keyword("background_get_transparent", darkBlue, true),
new Keyword("background_get_smooth", darkBlue, true),
new Keyword("background_get_preload", darkBlue, true),
new Keyword("background_save", darkBlue, true),
new Keyword("font_exists", darkBlue, true),
new Keyword("font_get_name", darkBlue, true),
new Keyword("font_get_fontname", darkBlue, true),
new Keyword("font_get_bold", darkBlue, true),
new Keyword("font_get_italic", darkBlue, true),
new Keyword("font_get_first", darkBlue, true),
new Keyword("font_get_last", darkBlue, true),
new Keyword("path_exists", darkBlue, true),
new Keyword("path_get_name", darkBlue, true),
new Keyword("path_get_length", darkBlue, true),
new Keyword("path_get_kind", darkBlue, true),
new Keyword("path_get_closed", darkBlue, true),
new Keyword("path_get_precision", darkBlue, true),
new Keyword("path_get_number", darkBlue, true),
new Keyword("path_get_point_x", darkBlue, true),
new Keyword("path_get_point_y", darkBlue, true),
new Keyword("path_get_point_speed", darkBlue, true),
new Keyword("path_get_x", darkBlue, true),
new Keyword("path_get_y", darkBlue, true),
new Keyword("path_get_speed", darkBlue, true),
new Keyword("script_exists", darkBlue, true),
new Keyword("script_get_name", darkBlue, true),
new Keyword("script_get_text", darkBlue, true),
new Keyword("timeline_exists", darkBlue, true),
new Keyword("timeline_get_name", darkBlue, true),
new Keyword("object_exists", darkBlue, true),
new Keyword("object_get_name", darkBlue, true),
new Keyword("object_get_sprite", darkBlue, true),
new Keyword("object_get_solid", darkBlue, true),
new Keyword("object_get_visible", darkBlue, true),
new Keyword("object_get_depth", darkBlue, true),
new Keyword("object_get_persistent", darkBlue, true),
new Keyword("object_get_mask", darkBlue, true),
new Keyword("object_get_parent", darkBlue, true),
new Keyword("object_is_ancestor", darkBlue, true),
new Keyword("room_exists", darkBlue, true),
new Keyword("room_get_name", darkBlue, true),
new Keyword("sprite_set_offset", darkBlue, true),
new Keyword("sprite_set_bbox_mode", darkBlue, true),
new Keyword("sprite_set_bbox", darkBlue, true),
new Keyword("sprite_set_precise", darkBlue, true),
new Keyword("sprite_duplicate", darkBlue, true),
new Keyword("sprite_assign", darkBlue, true),
new Keyword("sprite_merge", darkBlue, true),
new Keyword("sprite_add", darkBlue, true),
new Keyword("sprite_replace", darkBlue, true),
new Keyword("sprite_add_alpha", darkBlue, true),
new Keyword("sprite_replace_alpha", darkBlue, true),
new Keyword("sprite_create_from_screen", darkBlue, true),
new Keyword("sprite_add_from_screen", darkBlue, true),
new Keyword("sprite_create_from_surface", darkBlue, true),
new Keyword("sprite_add_from_surface", darkBlue, true),
new Keyword("sprite_delete", darkBlue, true),
new Keyword("sprite_set_alpha_from_sprite", darkBlue, true),
new Keyword("sound_add", darkBlue, true),
new Keyword("sound_replace", darkBlue, true),
new Keyword("sound_delete", darkBlue, true),
new Keyword("background_duplicate", darkBlue, true),
new Keyword("background_assign", darkBlue, true),
new Keyword("background_add", darkBlue, true),
new Keyword("background_replace", darkBlue, true),
new Keyword("background_add_alpha", darkBlue, true),
new Keyword("background_replace_alpha", darkBlue, true),
new Keyword("background_create_color", darkBlue, true),
new Keyword("background_create_gradient", darkBlue, true),
new Keyword("background_create_from_screen", darkBlue, true),
new Keyword("background_create_from_surface", darkBlue, true),
new Keyword("background_delete", darkBlue, true),
new Keyword("background_set_alpha_from_background", darkBlue, true),
new Keyword("font_add", darkBlue, true),
new Keyword("font_add_sprite", darkBlue, true),
new Keyword("font_replace", darkBlue, true),
new Keyword("font_replace_sprite", darkBlue, true),
new Keyword("font_delete", darkBlue, true),
new Keyword("path_set_kind", darkBlue, true),
new Keyword("path_set_closed", darkBlue, true),
new Keyword("path_set_precision", darkBlue, true),
new Keyword("path_add", darkBlue, true),
new Keyword("path_assign", darkBlue, true),
new Keyword("path_duplicate", darkBlue, true),
new Keyword("path_append", darkBlue, true),
new Keyword("path_delete", darkBlue, true),
new Keyword("path_add_point", darkBlue, true),
new Keyword("path_insert_point", darkBlue, true),
new Keyword("path_change_point", darkBlue, true),
new Keyword("path_delete_point", darkBlue, true),
new Keyword("path_clear_points", darkBlue, true),
new Keyword("path_reverse", darkBlue, true),
new Keyword("path_mirror", darkBlue, true),
new Keyword("path_flip", darkBlue, true),
new Keyword("path_rotate", darkBlue, true),
new Keyword("path_scale", darkBlue, true),
new Keyword("path_shift", darkBlue, true),
new Keyword("execute_string", darkBlue, true),
new Keyword("execute_file", darkBlue, true),
new Keyword("script_execute", darkBlue, true),
new Keyword("timeline_add", darkBlue, true),
new Keyword("timeline_delete", darkBlue, true),
new Keyword("timeline_moment_clear", darkBlue, true),
new Keyword("timeline_moment_add", darkBlue, true),
new Keyword("object_set_sprite", darkBlue, true),
new Keyword("object_set_solid", darkBlue, true),
new Keyword("object_set_visible", darkBlue, true),
new Keyword("object_set_depth", darkBlue, true),
new Keyword("object_set_persistent", darkBlue, true),
new Keyword("object_set_mask", darkBlue, true),
new Keyword("object_set_parent", darkBlue, true),
new Keyword("object_add", darkBlue, true),
new Keyword("object_delete", darkBlue, true),
new Keyword("object_event_clear", darkBlue, true),
new Keyword("object_event_add", darkBlue, true),
new Keyword("room_set_width", darkBlue, true),
new Keyword("room_set_height", darkBlue, true),
new Keyword("room_set_caption", darkBlue, true),
new Keyword("room_set_persistent", darkBlue, true),
new Keyword("room_set_code", darkBlue, true),
new Keyword("room_set_background_color", darkBlue, true),
new Keyword("room_set_background", darkBlue, true),
new Keyword("room_set_view", darkBlue, true),
new Keyword("room_set_view_enabled", darkBlue, true),
new Keyword("room_add", darkBlue, true),
new Keyword("room_duplicate", darkBlue, true),
new Keyword("room_assign", darkBlue, true),
new Keyword("room_instance_add", darkBlue, true),
new Keyword("room_instance_clear", darkBlue, true),
new Keyword("room_tile_add", darkBlue, true),
new Keyword("room_tile_add_ext", darkBlue, true),
new Keyword("room_tile_clear", darkBlue, true),
new Keyword("file_text_open_read", darkBlue, true),
new Keyword("file_text_open_write", darkBlue, true),
new Keyword("file_text_open_append", darkBlue, true),
new Keyword("file_text_close", darkBlue, true),
new Keyword("file_text_write_string", darkBlue, true),
new Keyword("file_text_write_real", darkBlue, true),
new Keyword("file_text_writeln", darkBlue, true),
new Keyword("file_text_read_string", darkBlue, true),
new Keyword("file_text_read_real", darkBlue, true),
new Keyword("file_text_readln", darkBlue, true),
new Keyword("file_text_eof", darkBlue, true),
new Keyword("file_exists", darkBlue, true),
new Keyword("file_delete", darkBlue, true),
new Keyword("file_rename", darkBlue, true),
new Keyword("file_copy", darkBlue, true),
new Keyword("directory_exists", darkBlue, true),
new Keyword("directory_create", darkBlue, true),
new Keyword("file_find_first", darkBlue, true),
new Keyword("file_find_next", darkBlue, true),
new Keyword("file_find_close", darkBlue, true),
new Keyword("file_attributes", darkBlue, true),
new Keyword("filename_name", darkBlue, true),
new Keyword("filename_path", darkBlue, true),
new Keyword("filename_dir", darkBlue, true),
new Keyword("filename_drive", darkBlue, true),
new Keyword("filename_ext", darkBlue, true),
new Keyword("filename_change_ext", darkBlue, true),
new Keyword("file_bin_open", darkBlue, true),
new Keyword("file_bin_rewrite", darkBlue, true),
new Keyword("file_bin_close", darkBlue, true),
new Keyword("file_bin_position", darkBlue, true),
new Keyword("file_bin_size", darkBlue, true),
new Keyword("file_bin_seek", darkBlue, true),
new Keyword("file_bin_write_byte", darkBlue, true),
new Keyword("file_bin_read_byte", darkBlue, true),
new Keyword("export_include_file", darkBlue, true),
new Keyword("export_include_file_location", darkBlue, true),
new Keyword("discard_include_file", darkBlue, true),
new Keyword("parameter_count", darkBlue, true),
new Keyword("parameter_string", darkBlue, true),
new Keyword("environment_get_variable", darkBlue, true),
new Keyword("fa_readonly", darkBlue),
new Keyword("fa_hidden", darkBlue),
new Keyword("fa_sysfile", darkBlue),
new Keyword("fa_volumeid", darkBlue),
new Keyword("fa_directory", darkBlue),
new Keyword("fa_archive", darkBlue),
new Keyword("game_id", darkBlue),
new Keyword("working_directory", darkBlue),
new Keyword("temp_directory", darkBlue),
new Keyword("program_directory", darkBlue),
new Keyword("registry_write_string", darkBlue, true),
new Keyword("registry_write_real", darkBlue, true),
new Keyword("registry_read_string", darkBlue, true),
new Keyword("registry_read_real", darkBlue, true),
new Keyword("registry_exists", darkBlue, true),
new Keyword("registry_write_string_ext", darkBlue, true),
new Keyword("registry_write_real_ext", darkBlue, true),
new Keyword("registry_read_string_ext", darkBlue, true),
new Keyword("registry_read_real_ext", darkBlue, true),
new Keyword("registry_exists_ext", darkBlue, true),
new Keyword("registry_set_root", darkBlue, true),
new Keyword("ini_open", darkBlue, true),
new Keyword("ini_close", darkBlue, true),
new Keyword("ini_read_string", darkBlue, true),
new Keyword("ini_read_real", darkBlue, true),
new Keyword("ini_write_string", darkBlue, true),
new Keyword("ini_write_real", darkBlue, true),
new Keyword("ini_key_exists", darkBlue, true),
new Keyword("ini_section_exists", darkBlue, true),
new Keyword("ini_key_delete", darkBlue, true),
new Keyword("ini_section_delete", darkBlue, true),
new Keyword("execute_program", darkBlue, true),
new Keyword("execute_shell", darkBlue, true),
new Keyword("secure_mode", darkBlue),
new Keyword("ds_set_precision", darkBlue, true),
new Keyword("ds_stack_create", darkBlue, true),
new Keyword("ds_stack_destroy", darkBlue, true),
new Keyword("ds_stack_clear", darkBlue, true),
new Keyword("ds_stack_copy", darkBlue, true),
new Keyword("ds_stack_size", darkBlue, true),
new Keyword("ds_stack_empty", darkBlue, true),
new Keyword("ds_stack_push", darkBlue, true),
new Keyword("ds_stack_pop", darkBlue, true),
new Keyword("ds_stack_top", darkBlue, true),
new Keyword("ds_stack_write", darkBlue, true),
new Keyword("ds_stack_read", darkBlue, true),
new Keyword("ds_queue_create", darkBlue, true),
new Keyword("ds_queue_destroy", darkBlue, true),
new Keyword("ds_queue_clear", darkBlue, true),
new Keyword("ds_queue_copy", darkBlue, true),
new Keyword("ds_queue_size", darkBlue, true),
new Keyword("ds_queue_empty", darkBlue, true),
new Keyword("ds_queue_enqueue", darkBlue, true),
new Keyword("ds_queue_dequeue", darkBlue, true),
new Keyword("ds_queue_head", darkBlue, true),
new Keyword("ds_queue_tail", darkBlue, true),
new Keyword("ds_queue_write", darkBlue, true),
new Keyword("ds_queue_read", darkBlue, true),
new Keyword("ds_list_create", darkBlue, true),
new Keyword("ds_list_destroy", darkBlue, true),
new Keyword("ds_list_clear", darkBlue, true),
new Keyword("ds_list_copy", darkBlue, true),
new Keyword("ds_list_size", darkBlue, true),
new Keyword("ds_list_empty", darkBlue, true),
new Keyword("ds_list_add", darkBlue, true),
new Keyword("ds_list_insert", darkBlue, true),
new Keyword("ds_list_replace", darkBlue, true),
new Keyword("ds_list_delete", darkBlue, true),
new Keyword("ds_list_find_index", darkBlue, true),
new Keyword("ds_list_find_value", darkBlue, true),
new Keyword("ds_list_sort", darkBlue, true),
new Keyword("ds_list_shuffle", darkBlue, true),
new Keyword("ds_list_write", darkBlue, true),
new Keyword("ds_list_read", darkBlue, true),
new Keyword("ds_map_create", darkBlue, true),
new Keyword("ds_map_destroy", darkBlue, true),
new Keyword("ds_map_clear", darkBlue, true),
new Keyword("ds_map_copy", darkBlue, true),
new Keyword("ds_map_size", darkBlue, true),
new Keyword("ds_map_empty", darkBlue, true),
new Keyword("ds_map_add", darkBlue, true),
new Keyword("ds_map_replace", darkBlue, true),
new Keyword("ds_map_delete", darkBlue, true),
new Keyword("ds_map_exists", darkBlue, true),
new Keyword("ds_map_find_value", darkBlue, true),
new Keyword("ds_map_find_previous", darkBlue, true),
new Keyword("ds_map_find_next", darkBlue, true),
new Keyword("ds_map_find_first", darkBlue, true),
new Keyword("ds_map_find_last", darkBlue, true),
new Keyword("ds_map_write", darkBlue, true),
new Keyword("ds_map_read", darkBlue, true),
new Keyword("ds_priority_create", darkBlue, true),
new Keyword("ds_priority_destroy", darkBlue, true),
new Keyword("ds_priority_clear", darkBlue, true),
new Keyword("ds_priority_copy", darkBlue, true),
new Keyword("ds_priority_size", darkBlue, true),
new Keyword("ds_priority_empty", darkBlue, true),
new Keyword("ds_priority_add", darkBlue, true),
new Keyword("ds_priority_change_priority", darkBlue, true),
new Keyword("ds_priority_find_priority", darkBlue, true),
new Keyword("ds_priority_delete_value", darkBlue, true),
new Keyword("ds_priority_delete_min", darkBlue, true),
new Keyword("ds_priority_find_min", darkBlue, true),
new Keyword("ds_priority_delete_max", darkBlue, true),
new Keyword("ds_priority_find_max", darkBlue, true),
new Keyword("ds_priority_write", darkBlue, true),
new Keyword("ds_priority_read", darkBlue, true),
new Keyword("ds_grid_create", darkBlue, true),
new Keyword("ds_grid_destroy", darkBlue, true),
new Keyword("ds_grid_copy", darkBlue, true),
new Keyword("ds_grid_resize", darkBlue, true),
new Keyword("ds_grid_width", darkBlue, true),
new Keyword("ds_grid_height", darkBlue, true),
new Keyword("ds_grid_clear", darkBlue, true),
new Keyword("ds_grid_set", darkBlue, true),
new Keyword("ds_grid_add", darkBlue, true),
new Keyword("ds_grid_multiply", darkBlue, true),
new Keyword("ds_grid_set_region", darkBlue, true),
new Keyword("ds_grid_add_region", darkBlue, true),
new Keyword("ds_grid_multiply_region", darkBlue, true),
new Keyword("ds_grid_set_disk", darkBlue, true),
new Keyword("ds_grid_add_disk", darkBlue, true),
new Keyword("ds_grid_multiply_disk", darkBlue, true),
new Keyword("ds_grid_set_grid_region", darkBlue, true),
new Keyword("ds_grid_add_grid_region", darkBlue, true),
new Keyword("ds_grid_multiply_grid_region", darkBlue, true),
new Keyword("ds_grid_get", darkBlue, true),
new Keyword("ds_grid_get_sum", darkBlue, true),
new Keyword("ds_grid_get_max", darkBlue, true),
new Keyword("ds_grid_get_min", darkBlue, true),
new Keyword("ds_grid_get_mean", darkBlue, true),
new Keyword("ds_grid_get_disk_sum", darkBlue, true),
new Keyword("ds_grid_get_disk_min", darkBlue, true),
new Keyword("ds_grid_get_disk_max", darkBlue, true),
new Keyword("ds_grid_get_disk_mean", darkBlue, true),
new Keyword("ds_grid_value_exists", darkBlue, true),
new Keyword("ds_grid_value_x", darkBlue, true),
new Keyword("ds_grid_value_y", darkBlue, true),
new Keyword("ds_grid_value_disk_exists", darkBlue, true),
new Keyword("ds_grid_value_disk_x", darkBlue, true),
new Keyword("ds_grid_value_disk_y", darkBlue, true),
new Keyword("ds_grid_shuffle", darkBlue, true),
new Keyword("ds_grid_write", darkBlue, true),
new Keyword("ds_grid_read", darkBlue, true),
new Keyword("effect_create_below", darkBlue, true),
new Keyword("effect_create_above", darkBlue, true),
new Keyword("effect_clear", darkBlue, true),
new Keyword("ef_explosion", darkBlue),
new Keyword("ef_ring", darkBlue),
new Keyword("ef_ellipse", darkBlue),
new Keyword("ef_firework", darkBlue),
new Keyword("ef_smoke", darkBlue),
new Keyword("ef_smokeup", darkBlue),
new Keyword("ef_star", darkBlue),
new Keyword("ef_spark", darkBlue),
new Keyword("ef_flare", darkBlue),
new Keyword("ef_cloud", darkBlue),
new Keyword("ef_rain", darkBlue),
new Keyword("ef_snow", darkBlue),
new Keyword("part_type_create", darkBlue, true),
new Keyword("part_type_destroy", darkBlue, true),
new Keyword("part_type_exists", darkBlue, true),
new Keyword("part_type_clear", darkBlue, true),
new Keyword("part_type_shape", darkBlue, true),
new Keyword("part_type_sprite", darkBlue, true),
new Keyword("part_type_size", darkBlue, true),
new Keyword("part_type_scale", darkBlue, true),
new Keyword("part_type_orientation", darkBlue, true),
new Keyword("part_type_life", darkBlue, true),
new Keyword("part_type_step", darkBlue, true),
new Keyword("part_type_death", darkBlue, true),
new Keyword("part_type_speed", darkBlue, true),
new Keyword("part_type_direction", darkBlue, true),
new Keyword("part_type_gravity", darkBlue, true),
new Keyword("part_type_color1", darkBlue, true),
new Keyword("part_type_color2", darkBlue, true),
new Keyword("part_type_color3", darkBlue, true),
new Keyword("part_type_color_mix", darkBlue, true),
new Keyword("part_type_color_rgb", darkBlue, true),
new Keyword("part_type_color_hsv", darkBlue, true),
new Keyword("part_type_alpha1", darkBlue, true),
new Keyword("part_type_alpha2", darkBlue, true),
new Keyword("part_type_alpha3", darkBlue, true),
new Keyword("part_type_blend", darkBlue, true),
new Keyword("pt_shape_pixel", darkBlue),
new Keyword("pt_shape_disk", darkBlue),
new Keyword("pt_shape_square", darkBlue),
new Keyword("pt_shape_line", darkBlue),
new Keyword("pt_shape_star", darkBlue),
new Keyword("pt_shape_circle", darkBlue),
new Keyword("pt_shape_ring", darkBlue),
new Keyword("pt_shape_sphere", darkBlue),
new Keyword("pt_shape_flare", darkBlue),
new Keyword("pt_shape_spark", darkBlue),
new Keyword("pt_shape_explosion", darkBlue),
new Keyword("pt_shape_cloud", darkBlue),
new Keyword("pt_shape_smoke", darkBlue),
new Keyword("part_system_create", darkBlue, true),
new Keyword("part_system_destroy", darkBlue, true),
new Keyword("part_system_exists", darkBlue, true),
new Keyword("part_system_clear", darkBlue, true),
new Keyword("part_system_draw_order", darkBlue, true),
new Keyword("part_system_depth", darkBlue, true),
new Keyword("part_system_position", darkBlue, true),
new Keyword("part_system_automatic_update", darkBlue, true),
new Keyword("part_system_automatic_draw", darkBlue, true),
new Keyword("part_system_update", darkBlue, true),
new Keyword("part_system_drawit", darkBlue, true),

new Keyword("part_particles_create", darkBlue, true),
new Keyword("part_particles_create_color", darkBlue, true),
new Keyword("part_particles_clear", darkBlue, true),
new Keyword("part_particles_count", darkBlue, true),
new Keyword("part_emitter_create", darkBlue, true),
new Keyword("part_emitter_destroy", darkBlue, true),
new Keyword("part_emitter_destroy_all", darkBlue, true),
new Keyword("part_emitter_exists", darkBlue, true),
new Keyword("part_emitter_clear", darkBlue, true),
new Keyword("part_emitter_region", darkBlue, true),
new Keyword("part_emitter_burst", darkBlue, true),
new Keyword("part_emitter_stream", darkBlue, true),
new Keyword("ps_distr_linear", darkBlue),
new Keyword("ps_distr_gaussian", darkBlue),
new Keyword("ps_distr_invgaussian", darkBlue),
new Keyword("ps_shape_rectangle", darkBlue),
new Keyword("ps_shape_ellipse", darkBlue),
new Keyword("ps_shape_diamond", darkBlue),
new Keyword("ps_shape_line", darkBlue),
new Keyword("part_attractor_create", darkBlue, true),
new Keyword("part_attractor_destroy", darkBlue, true),
new Keyword("part_attractor_destroy_all", darkBlue, true),
new Keyword("part_attractor_exists", darkBlue, true),
new Keyword("part_attractor_clear", darkBlue, true),
new Keyword("part_attractor_position", darkBlue, true),
new Keyword("part_attractor_force", darkBlue, true),
new Keyword("ps_force_constant", darkBlue),
new Keyword("ps_force_linear", darkBlue),
new Keyword("ps_force_quadratic", darkBlue),
new Keyword("part_destroyer_create", darkBlue, true),
new Keyword("part_destroyer_destroy", darkBlue, true),
new Keyword("part_destroyer_destroy_all", darkBlue, true),
new Keyword("part_destroyer_exists", darkBlue, true),
new Keyword("part_destroyer_clear", darkBlue, true),
new Keyword("part_destroyer_region", darkBlue, true),
new Keyword("part_deflector_create", darkBlue, true),
new Keyword("part_deflector_destroy", darkBlue, true),
new Keyword("part_deflector_destroy_all", darkBlue, true),
new Keyword("part_deflector_exists", darkBlue, true),
new Keyword("part_deflector_clear", darkBlue, true),
new Keyword("part_deflector_region", darkBlue, true),
new Keyword("part_deflector_kind", darkBlue, true),
new Keyword("part_deflector_friction", darkBlue, true),
new Keyword("ps_deflect_vertical", darkBlue),
new Keyword("ps_deflect_horizontal", darkBlue),
new Keyword("part_changer_create", darkBlue, true),
new Keyword("part_changer_destroy", darkBlue, true),
new Keyword("part_changer_destroy_all", darkBlue, true),
new Keyword("part_changer_exists", darkBlue, true),
new Keyword("part_changer_clear", darkBlue, true),
new Keyword("part_changer_region", darkBlue, true),
new Keyword("part_changer_kind", darkBlue, true),
new Keyword("part_changer_types", darkBlue, true),
new Keyword("ps_change_all", darkBlue),
new Keyword("ps_change_shape", darkBlue),
new Keyword("ps_change_motion", darkBlue),
new Keyword("mplay_init_ipx", darkBlue, true),
new Keyword("mplay_init_tcpip", darkBlue, true),
new Keyword("mplay_init_modem", darkBlue, true),
new Keyword("mplay_init_serial", darkBlue, true),
new Keyword("mplay_connect_status", darkBlue, true),
new Keyword("mplay_end", darkBlue, true),
new Keyword("mplay_ipaddress", darkBlue, true),
new Keyword("mplay_session_mode", darkBlue, true),
new Keyword("mplay_session_create", darkBlue, true),
new Keyword("mplay_session_find", darkBlue, true),
new Keyword("mplay_session_name", darkBlue, true),
new Keyword("mplay_session_join", darkBlue, true),
new Keyword("mplay_session_status", darkBlue, true),
new Keyword("mplay_session_end", darkBlue, true),
new Keyword("mplay_player_find", darkBlue, true),
new Keyword("mplay_player_name", darkBlue, true),
new Keyword("mplay_player_id", darkBlue, true),
new Keyword("mplay_data_write", darkBlue, true),
new Keyword("mplay_data_read", darkBlue, true),
new Keyword("mplay_data_mode", darkBlue, true),
new Keyword("mplay_message_send", darkBlue, true),
new Keyword("mplay_message_send_guaranteed", darkBlue, true),
new Keyword("mplay_message_receive", darkBlue, true),
new Keyword("mplay_message_id", darkBlue, true),
new Keyword("mplay_message_value", darkBlue, true),
new Keyword("mplay_message_player", darkBlue, true),
new Keyword("mplay_message_name", darkBlue, true),
new Keyword("mplay_message_count", darkBlue, true),
new Keyword("mplay_message_clear", darkBlue, true),
new Keyword("external_call", darkBlue, true),
new Keyword("external_define", darkBlue, true),
new Keyword("external_free", darkBlue, true),
new Keyword("window_handle", darkBlue, true),
new Keyword("ty_real", darkBlue),
new Keyword("ty_string", darkBlue),
new Keyword("dll_cdecl", darkBlue),
new Keyword("dll_stdcall", darkBlue),
new Keyword("d3d_start", darkBlue, true),
new Keyword("d3d_end", darkBlue, true),
new Keyword("d3d_set_hidden", darkBlue, true),
new Keyword("d3d_set_perspective", darkBlue, true),
new Keyword("d3d_set_depth", darkBlue, true),
new Keyword("d3d_primitive_begin", darkBlue, true),
new Keyword("d3d_vertex", darkBlue, true),
new Keyword("d3d_vertex_color", darkBlue, true),
new Keyword("d3d_primitive_end", darkBlue, true),
new Keyword("d3d_primitive_begin_texture", darkBlue, true),
new Keyword("d3d_vertex_texture", darkBlue, true),
new Keyword("d3d_vertex_texture_color", darkBlue, true),
new Keyword("d3d_draw_block", darkBlue, true),
new Keyword("d3d_draw_cylinder", darkBlue, true),
new Keyword("d3d_draw_cone", darkBlue, true),
new Keyword("d3d_draw_ellipsoid", darkBlue, true),
new Keyword("d3d_draw_wall", darkBlue, true),
new Keyword("d3d_draw_floor", darkBlue, true),
new Keyword("d3d_set_projection", darkBlue, true),
new Keyword("d3d_set_projection_ext", darkBlue, true),
new Keyword("d3d_set_projection_ortho", darkBlue, true),
new Keyword("d3d_set_projection_perspective", darkBlue, true),
new Keyword("d3d_transform_set_identity", darkBlue, true),
new Keyword("d3d_transform_set_translation", darkBlue, true),
new Keyword("d3d_transform_set_scaling", darkBlue, true),
new Keyword("d3d_transform_set_rotation_x", darkBlue, true),
new Keyword("d3d_transform_set_rotation_y", darkBlue, true),
new Keyword("d3d_transform_set_rotation_z", darkBlue, true),
new Keyword("d3d_transform_set_rotation_axis", darkBlue, true),
new Keyword("d3d_transform_add_translation", darkBlue, true),
new Keyword("d3d_transform_add_scaling", darkBlue, true),
new Keyword("d3d_transform_add_rotation_x", darkBlue, true),
new Keyword("d3d_transform_add_rotation_y", darkBlue, true),
new Keyword("d3d_transform_add_rotation_z", darkBlue, true),
new Keyword("d3d_transform_add_rotation_axis", darkBlue, true),
new Keyword("d3d_transform_stack_clear", darkBlue, true),
new Keyword("d3d_transform_stack_empty", darkBlue, true),
new Keyword("d3d_transform_stack_push", darkBlue, true),
new Keyword("d3d_transform_stack_pop", darkBlue, true),
new Keyword("d3d_transform_stack_top", darkBlue, true),
new Keyword("d3d_transform_stack_discard", darkBlue, true),
new Keyword("d3d_set_fog", darkBlue, true),
new Keyword("d3d_set_lighting", darkBlue, true),
new Keyword("d3d_set_shading", darkBlue, true),
new Keyword("d3d_set_culling", darkBlue, true),
new Keyword("d3d_light_define_direction", darkBlue, true),
new Keyword("d3d_light_define_point", darkBlue, true),
new Keyword("d3d_light_enable", darkBlue, true),
new Keyword("d3d_vertex_normal", darkBlue, true),
new Keyword("d3d_vertex_normal_color", darkBlue, true),
new Keyword("d3d_vertex_normal_texture", darkBlue, true),
new Keyword("d3d_vertex_normal_texture_color", darkBlue, true),

new Keyword("d3d_model_create", darkBlue, true),
new Keyword("d3d_model_destroy", darkBlue, true),
new Keyword("d3d_model_clear", darkBlue, true),
new Keyword("d3d_model_save", darkBlue, true),
new Keyword("d3d_model_load", darkBlue, true),
new Keyword("d3d_model_draw", darkBlue, true),

new Keyword("d3d_model_primitive_begin", darkBlue, true),
new Keyword("d3d_model_vertex", darkBlue, true),
new Keyword("d3d_model_vertex_color", darkBlue, true),
new Keyword("d3d_model_vertex_texture", darkBlue, true),
new Keyword("d3d_model_vertex_texture_color", darkBlue, true),
new Keyword("d3d_model_vertex_normal", darkBlue, true),
new Keyword("d3d_model_vertex_normal_color", darkBlue, true),
new Keyword("d3d_model_vertex_normal_texture", darkBlue, true),
new Keyword("d3d_model_vertex_normal_texture_color", darkBlue, true),
new Keyword("d3d_model_primitive_end", darkBlue, true),

new Keyword("d3d_model_block", darkBlue, true),
new Keyword("d3d_model_cylinder", darkBlue, true),
new Keyword("d3d_model_cone", darkBlue, true),
new Keyword("d3d_model_ellipsoid", darkBlue, true),
new Keyword("d3d_model_wall", darkBlue, true),
new Keyword("d3d_model_floor", darkBlue, true)};

    @Override
    public Keyword[] getKeywords() {
        return keywords;
    }
    
}