/*
 * CmdAction.java
 *
 * Created on 05 November 2007, 23:04
 */

package org.gcreator.actions.platform;

import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JPanel;
import org.gcreator.actions.Action;
import org.gcreator.actions.ActionPattern;

/**
 *
 * @author  Ali
 */
public class CmdAction extends ActionPattern {
    
    String text = "";
    
    
    
    public JComponent createNewPanel(Action action) {
//        initComponents();
       // return this;
        
        return new test();
    }

     
    public String generateGCL(JComponent panel) {
        return "Platform.printCmd(\""+text+"\");";
    }

     
    public String writeXml(JComponent panel) {
        return super.writeXml(panel);
    }
    
    class test extends JPanel {
        
        test(){
        initComponents();
        this.jTextField1.setText(text);
        }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("Command line message:");

        jTextField1.setText("Hello World");

        jCheckBox1.setText("As Error (Will be treated as an error on the command line)");

        jLabel2.setText("<html>This action will use the platforms command prompt to write a message. The message is enclosed by \" when compiled so no need to use them unless you want to add variables. To display the value of a variable use \"+variable+\"</html>");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(jCheckBox1)
                        .addContainerGap(54, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jTextField1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .addContainerGap(287, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jCheckBox1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    }

    public void setStandardImage(ImageIcon icon) {
       // throw new UnsupportedOperationException("Not supported yet.");
    }
    
    public String getStandardText(JComponent panel){
        if(panel != null&& panel instanceof test){
            test editor = (test) panel;
           text = editor.jTextField1.getText();
        } 
        else
            text = "";
        return "CMD: "+text;
    }

    public ImageIcon getStandardImage() {
       return new ImageIcon(getClass().getResource("/org/gcreator/actions/images/Blank_action.png"));
    }
}
