/*
 * GlobalSettings.java
 *
 * Created on 10 de Outubro de 2007, 14:49
 */

package components;

import org.gcreator.core.*;
import managers.*;

/**
 *
 * @author  Luís
 */
public class GlobalSettings extends TabPanel {
    
    /** Creates new form GlobalSettings */
    public GlobalSettings() {
        initComponents();
        jTabbedPane1.add("Language", new LanguageTab());
        if(gcreator.window.items[MenuSupporter.GenerateMenuItemId(5, 0)].isSelected())
            jRadioButton1.setSelected(true);
        else if(gcreator.window.items[MenuSupporter.GenerateMenuItemId(5, 1)].isSelected())
            jRadioButton2.setSelected(true);
        else if(gcreator.window.items[MenuSupporter.GenerateMenuItemId(5, 2)].isSelected())
            jRadioButton3.setSelected(true);
        if(gcreator.window.items[MenuSupporter.GenerateMenuItemId(6, 0)].isSelected())
            jRadioButton4.setSelected(true);
        else if(gcreator.window.items[MenuSupporter.GenerateMenuItemId(6, 1)].isSelected())
            jRadioButton5.setSelected(true);
        else if(gcreator.window.items[MenuSupporter.GenerateMenuItemId(6, 2)].isSelected())
            jRadioButton6.setSelected(true);
        else if(gcreator.window.items[MenuSupporter.GenerateMenuItemId(6, 3)].isSelected())
            jRadioButton7.setSelected(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jLabel1.setText("Choose look&feel");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Native look");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Cross-platform look");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Motif look");

        jLabel2.setText("Choose display mode");

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("Tabs (Top)");

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setText("Tabs (Left)");

        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setText("Tabs (Bottom)");

        buttonGroup2.add(jRadioButton7);
        jRadioButton7.setText("Tabs (Right)");

        buttonGroup2.add(jRadioButton8);
        jRadioButton8.setText("MDI");

        jButton1.setText("Apply");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton3)))
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton5)
                            .addComponent(jRadioButton4)
                            .addComponent(jRadioButton6)
                            .addComponent(jRadioButton7)
                            .addComponent(jRadioButton8))))
                .addContainerGap(165, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(235, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton8)
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(236, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Layout", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        gcreator.window.items[MenuSupporter.GenerateMenuItemId(5, 0)].setSelected(jRadioButton1.isSelected());
        gcreator.window.items[MenuSupporter.GenerateMenuItemId(5, 1)].setSelected(jRadioButton2.isSelected());
        gcreator.window.items[MenuSupporter.GenerateMenuItemId(5, 2)].setSelected(jRadioButton3.isSelected());
        gcreator.window.items[MenuSupporter.GenerateMenuItemId(6, 0)].setSelected(jRadioButton4.isSelected());
        gcreator.window.items[MenuSupporter.GenerateMenuItemId(6, 1)].setSelected(jRadioButton5.isSelected());
        gcreator.window.items[MenuSupporter.GenerateMenuItemId(6, 2)].setSelected(jRadioButton6.isSelected());
        gcreator.window.items[MenuSupporter.GenerateMenuItemId(6, 3)].setSelected(jRadioButton7.isSelected());
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
    
}
