/*
 * Copyright (C) 2007-2008 Luís Reis <luiscubal@gmail.com>
 * Copyright (C) 2007-2008 TGMG <thegamemakerguru@hotmail.com>
 * Copyright (C) 2008 Serge Humphrey <bob@bobtheblueberry.com>
 * 
 * This file is part of G-Creator.
 * G-Creator is free software and comes with ABSOLUTELY NO WARRANTY.
 * See LICENSE for more details.
 */
package org.gcreator.components;

import org.gcreator.core.*;
import org.gcreator.managers.*;

import java.awt.*;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;

/**
 *
 * @author  Luís
 */
public class GlobalSettings extends TabPanel {
    
    boolean b = false;
    
    /** Creates new form GlobalSettings */
    public GlobalSettings(final String[] settings) {
        initComponents();
        jTabbedPane1.add("Language", new LanguageTab());
        jTabbedPane1.add("Toolbars", new ToolbarEditor());
        jTabbedPane1.add("Script Editor", new StyleThemePreferences());
        this.addComponentListener(new ComponentListener(){
            public void componentHidden(ComponentEvent evt){}
            public void componentShown(ComponentEvent evt){
                if (!b) {
                    jTabbedPane1.add("User interface", new PreferencesTab(settings));
                    b = true;
                }
            }
            public void componentMoved(ComponentEvent evt){}
            public void componentResized(ComponentEvent evt){}
        });
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    public void dispose(){
        int len = jTabbedPane1.getTabCount();
        for(int i = 0; i < len; i++){
            Component p = jTabbedPane1.getComponentAt(i);
            if(p instanceof OptionPanel)
                if(!((OptionPanel) p).dispose())
                    return;
        }
        super.dispose();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    public javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
    
}
