/*
 * NewJPanel.java
 *
 * Created on 24 de Agosto de 2007, 19:13
 */

package org.gcreator.components;

/**
 *
 * @author  Luís
 */
public class HelpTab extends TabPanel {
    
    /** Creates new form NewJPanel */
    public HelpTab() {
        this(0,0);
    }
    
    public HelpTab(int section, int part){
        initComponents();
        selectSection(section);
        selectPart(part);
    }
    
    public void openCurrentPart(){
        
    }
    
    public void selectSection(int section){
        jList1.setSelectedIndex(section);
        jList2.setSelectedIndex(-1);
        switch(section){
        case 0: jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "About Aurora", "What's Aurora", "What's new?", "Changing Aurora Settings"};
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        }); break;
        case 1: jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Creating a new project", "Managing project files", "Adding and removing resources", "The images", "The sounds", "The actors", "The scenes", "The game settings", "Building and Running the game project"};
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        }); break;
        case 2: jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Getting started with EGML" , "EGML for GML programmers", "The scripts", "The actions", "EGML tutorial", "EGML API"};
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        }); break;
        case 3: jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Getting started with AES", "Using the PluginHelper", "Using the VarsRegistry"};
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        }); break;
        }
    }
    
    public void selectPart(int part){
        jList2.setSelectedIndex(part);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jSplitPane2 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();

        jSplitPane1.setDividerLocation(150);

        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "About Aurora", "Working with Aurora", "The Extended Game Maker Language (EGML)", "The Aurora Extension System (AES)" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jList1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jList1MouseDragged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jSplitPane2.setTopComponent(jScrollPane1);

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jList2);

        jSplitPane2.setRightComponent(jScrollPane2);

        jSplitPane1.setLeftComponent(jSplitPane2);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jSplitPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jSplitPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        selectSection(jList1.getSelectedIndex());
    }//GEN-LAST:event_jList1MouseClicked

    private void jList1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseDragged
        selectSection(jList1.getSelectedIndex());
    }//GEN-LAST:event_jList1MouseDragged
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    // End of variables declaration//GEN-END:variables
    
}
