/*
 * Copyright (C) 2007-2008 Luís Reis <luiscubal@gmail.com>
 * Copyright (C) 2007-2008 TGMG <thegamemakerguru@hotmail.com>
 * Copyright (C) 2008 Serge Humphrey <bob@bobtheblueberry.com>
 * 
 * This file is part of G-Creator.
 * G-Creator is free software and comes with ABSOLUTELY NO WARRANTY.
 * See LICENSE for more details.
 */
package org.gcreator.components;

import java.awt.Color;
import java.awt.Component;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import org.gcreator.units.Dictionary;

/**
 *
 * @author  Luís
 */
public class LanguageTab extends TabPanel {
    private static final long serialVersionUID = 1;
    
    private class DictionaryRenderer extends JLabel implements ListCellRenderer{
        private DictionaryRenderer(){
            super();
            setOpaque(true);
        }
        
        @Override
        public Component getListCellRendererComponent(
                JList parent, Object dictionary, int index, boolean isSelected, boolean hasFocus){
            
            try{
                setText(((Dictionary) dictionary).getLanguage());
                setBackground(isSelected ? parent.getSelectionBackground() : parent.getBackground());
                setForeground(isSelected ? parent.getSelectionForeground() : parent.getForeground());
            }
            catch(Exception e){
                setText("INVALID");
                setBackground(Color.WHITE);
                setForeground(Color.RED);
            }
            
            return this;
        }
    }
    
    /** Creates new form LanguageTab */
    public LanguageTab() {
        initComponents();
        DefaultComboBoxModel model = new DefaultComboBoxModel(){
            @Override
            public int getSize(){
                return Dictionary.countDictionaries();
            }
            
            @Override
            public Object getElementAt(int index){
                return Dictionary.getDictionaries()[index];
            }
        };
        jComboBox1.setModel(model);
        jComboBox1.setRenderer(new DictionaryRenderer());
        //try{
        //if(LangSupporter.activeLang.getLanguage().equals(gcreator.panel.lang)) {
        //        jLabel4.setVisible(false);
        //    }
        //}
        //catch(Exception e){}
        //int l = 0;
        /*if(gcreator.panel.lang.equals("German")) {
            l = 1;
        }
        if(gcreator.panel.lang.equals("German (Old)")) {
            l = 2;
        }
        if(gcreator.panel.lang.equals("Portuguese (European)")) {
            l = 3;
        }
        if(gcreator.panel.lang.equals("Russian")) {
            l = 4;
        }
        if(gcreator.panel.lang.equals("Spanish")) {
            l = 5;
        }
        jComboBox1.setSelectedIndex(l);*/
        jComboBox1.setSelectedIndex(0);
        updateLanguage();
    }
    
    public void updateLanguage(){
        int l = jComboBox1.getSelectedIndex();
        Dictionary m;
        /*if(l==0) {
            m = new English();
        }
        else if(l==1) {
            m = new German();
        }
        else if(l==2) {
            m = new GermanOld();
        }
        else if(l==3) {
            m = new Portuguese();
        }
        else if(l==4) {
            m = new Russian();
        }
        else{
            m = new Spanish();
        }*/
        //jLabel1.setText(m.getEntry(47));
        //jLabel2.setText(m.getEntry(48));
        //jLabel3.setText(m.getStatus());
        //jLabel4.setText(m.getEntry(50));
        //jButton1.setText(m.getEntry(49));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("Language");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("Apply Language");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, 0, 329, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(240, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        updateLanguage();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //gcreator.panel.lang = (String) jComboBox1.getSelectedItem();
        //try{
        //    jLabel4.setVisible(!LangSupporter.activeLang.getLanguage().equals(gcreator.panel.lang));
        //}
        //catch(Exception e){
        //    
        //}
        Dictionary.activeDictionary = ((Dictionary) jComboBox1.getSelectedItem()).getShortName();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
}
