/*
 * Copyright (C) 2007-2008 Luís Reis <luiscubal@gmail.com>
 * Copyright (C) 2007-2008 TGMG <thegamemakerguru@hotmail.com>
 * Copyright (c) 2008 BobSerge or Bobistaken <serge_1994@hotmail.com>
 * 
 * This file is part of G-Creator.
 * G-Creator is free software and comes with ABSOLUTELY NO WARRANTY.
 * See LICENSE for more details.
 */
package org.gcreator.components;

import java.awt.BorderLayout;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.gcreator.components.scanning.JavaScriptTokenMarker;
//import org.gcreator.macro.Macro;

/**
 *
 * @author  Luís
 */
/*public class MacroEditor extends TabPanel {

    public Macro macro;
    public JEditTextArea editor;
    */
    /** Creates new form MacroEditor *//*
    public MacroEditor(Macro m) {
        initComponents();
        this.macro = m;
        editor = new JEditTextArea(null);
        editor.setTokenMarker(new JavaScriptTokenMarker());
        editor.setText(macro.javascript);
        editor.getDocument().addDocumentListener(new DocumentListener(){
            public void changedUpdate(DocumentEvent evt){
                update();
            }
            public void removeUpdate(DocumentEvent evt){
                update();
            }
            public void insertUpdate(DocumentEvent evt){
                update();
            }
            public void update(){
                macro.javascript = editor.getText();
            }
        });
        setLayout(new BorderLayout());
        add(BorderLayout.CENTER, editor);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     *//*
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}*/
