/*
 * NewFileGroup.java
 *
 * Created on 6 de Setembro de 2007, 11:20
 */

package org.gcreator.components;

import javax.swing.*;
import javax.swing.tree.*;

import org.gcreator.components.*;
import org.gcreator.components.impl.*;
import org.gcreator.core.*;

/**
 *
 * @author  Luís
 */

public class NewFileGroup extends TabPanel {
      
    public JTree tree;
    
    /** Creates new form NewFileGroup */
    
    public Model a1;
    public Model a2;
    public Model a3;
    
    public NewFileGroup() {
        initComponents();
        tree = new JTree(gcreator.window.top);
        //jScrollPane1.setViewportView(tree);
        DefaultTreeSelectionModel model = new DefaultTreeSelectionModel();
        model.setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
        tree.setSelectionModel(model);
        tree.setCellRenderer(gcreator.window.workspace.getCellRenderer());
        a1 = new Model() {
            String[] strings = {"Group", "Text file"};
            String[] truenames = {"/", "txt"};
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
            public String getTrueName(int i){ return truenames[i]; }
        };
        a2 = new Model() {
            String[] strings = {"Sprite", "Tileset", "Actor", "Scene", "EGML Script"};
            String[] truenames = {"sprite", "tileset", "actor", "scene", "egml"};
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
            public String getTrueName(int i){ return truenames[i]; }
        };
        a3 = new Model() {
            String[] strings = new String[]{"Java file", "C++ file", "C++ header file", "XML file"};
            String[] truenames = {"java", "cpp", "h", "xml"};
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
            public String getTrueName(int i){ return truenames[i]; }
        };
        jList2.setModel(a1);
        jList1.setSelectedIndex(0);
        //tree.addMouse
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        jLabel1.setText(org.gcreator.managers.LangSupporter.activeLang.getEntry(95));

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { org.gcreator.managers.LangSupporter.activeLang.getEntry(97), "Game items", "Development items" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        jList2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(jList2);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(0, 0, 0)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 174, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(jTextField1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButton1))))
                    .add(jLabel1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton1)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String val = ((Model) jList2.getModel()).getTrueName(jList2.getSelectedIndex());
        if(gcreator.window.getCurrentFolder()!=null)
            add(val);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        if(jList1.getSelectedIndex()==0)
            jList2.setModel(a1);
        else if(jList1.getSelectedIndex()==1)
            jList2.setModel(a2);
        else if(jList1.getSelectedIndex()==2)
            jList2.setModel(a3);
    }//GEN-LAST:event_jList1ValueChanged
    
    public org.gcreator.fileclass.Folder getCurrentFolder() {
        return gcreator.window.getCurrentFolder();
    }

    public org.gcreator.fileclass.Object getCurrentObject() {
        return gcreator.window.getCurrentObject();
    }
    
    public void add(String val){
        String name = jTextField1.getText();
        if(name.equals(""))
            name = "new";
        if(val.equals("/"))
            gcreator.window.addGroup(getCurrentFolder(), getCurrentFolder().newGroup(name));
        else
            gcreator.window.addFile(getCurrentFolder(), name, val);
        Aurwindow.workspace.updateUI();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JList jList1;
    public javax.swing.JList jList2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    
}
