/*
 * PreferencesTab.java
 *
 * Created on 3 de Abril de 2008, 20:34
 */
package org.gcreator.components;

import java.awt.Component;
import javax.swing.*;
import org.gcreator.core.*;
import org.gcreator.managers.*;

/**
 *
 * @author  Luís
 */
public class PreferencesTab extends OptionPanel {

    /** Creates new form PreferencesTab */
    public PreferencesTab(String[] settings) {
        initComponents();

        jComboBox1.setSelectedIndex(0);
        try {
            if (settings != null && settings[0] != null && settings[0].equals("Native")) {
                gcreator.window.look = 0;
            } else if (settings == null || settings[0] == null || settings[0].equals("Cross-platform")) {
                jComboBox1.setSelectedIndex(1);
                gcreator.window.look = 1;
            } else if (settings[0].equals("Motif")) {
                jComboBox1.setSelectedIndex(2);
                gcreator.window.look = 2;
            } else if (settings[0].equals("Metal")) {
                jComboBox1.setSelectedIndex(3);
                gcreator.window.look = 3;
            } else {
                jComboBox1.setSelectedIndex(1);
                gcreator.window.look = 1;
            }
        } catch (Exception e) {
            jComboBox1.setSelectedIndex(1);
            gcreator.window.look = 1;
        }
        
        jComboBox2.setSelectedIndex(0);
        
         if (settings[1].equals("MDI")) {
             jComboBox2.setSelectedIndex(4);
            //items[MenuSupporter.GenerateMenuItemId(6, 4)].setSelected(true);
            //onItemActionPerformed(6, 4, null);
        }
        if (settings[1].equals("Tabs (Left)")) {
            jComboBox2.setSelectedIndex(4);
            //items[MenuSupporter.GenerateMenuItemId(6, 1)].setSelected(true);
            //onItemActionPerformed(6, 1, null);
        }
        if (settings[1].equals("Tabs (Bottom)")) {
            jComboBox2.setSelectedIndex(4);
            //items[MenuSupporter.GenerateMenuItemId(6, 2)].setSelected(true);
            //onItemActionPerformed(6, 2, null);
        }
        if (settings[1].equals("Tabs (Right)")) {
            jComboBox2.setSelectedIndex(4);
            //items[MenuSupporter.GenerateMenuItemId(6, 3)].setSelected(true);
            //onItemActionPerformed(6, 3, null);
        }
        
        jCheckBox1.setSelected(Boolean.parseBoolean(settings[7]));
        jComboBox2ActionPerformed(null);
    }
    public DefaultComboBoxModel lafmodel = new DefaultComboBoxModel() {

                public String[] vals = new String[]{getLang(17), getLang(18), getLang(19), getLang(132)};

                public Object getElementAt(int pos) {
                    return vals[pos];
                }

                public int getSize() {
                    return vals.length;
                }
            };
    public DefaultComboBoxModel displaymodes = new DefaultComboBoxModel() {

                public String[] vals = new String[]{getLang(20), getLang(90), getLang(91), getLang(92),
                        getLang(21)};

                public Object getElementAt(int pos) {
                    return vals[pos];
                }

                public int getSize() {
                    return vals.length;
                }
            };

    public String getLang(int lang) {
        return LangSupporter.activeLang.getEntry(lang);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();

        jLabel1.setText(getLang(15));

        jComboBox1.setModel(lafmodel);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setText(getLang(16));

        jComboBox2.setModel(displaymodes);
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(LangSupporter.activeLang.getEntry(266)));

        jCheckBox1.setText("Antialiasing");
        jCheckBox1.setText(LangSupporter.activeLang.getEntry(259));
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("Spin Menu");
        jCheckBox2.setVisible(false);
        jCheckBox2.setEnabled(false);

        jCheckBox3.setText("High-Contrast");
        jCheckBox3.setVisible(false);
        jCheckBox3.setEnabled(false);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jCheckBox1)
                    .add(jCheckBox2)
                    .add(jCheckBox3))
                .addContainerGap(286, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jCheckBox1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jCheckBox2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jCheckBox3)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jLabel2))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jComboBox2, 0, 310, Short.MAX_VALUE)
                            .add(jComboBox1, 0, 310, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jComboBox2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        int sel = jComboBox1.getSelectedIndex();

        try {
            switch (sel) {
                case 0:
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    SwingUtilities.updateComponentTreeUI(gcreator.window);
                    if (gcreator.window.istabs) {
                        SwingUtilities.updateComponentTreeUI(gcreator.window.mdi);
                    } else {
                        SwingUtilities.updateComponentTreeUI(Aurwindow.tabs);
                    }
                    SwingUtilities.updateComponentTreeUI(gcreator.window.consolepopup);
                    gcreator.window.look = 0;
                    Aurwindow.workspace.updateUI();
                    break;
                case 1:
                    javax.swing.plaf.metal.MetalLookAndFeel.setCurrentTheme(new javax.swing.plaf.metal.OceanTheme());
                    UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
                    SwingUtilities.updateComponentTreeUI(gcreator.window);
                    if (gcreator.window.istabs) {
                        SwingUtilities.updateComponentTreeUI(gcreator.window.mdi);
                    } else {
                        SwingUtilities.updateComponentTreeUI(Aurwindow.tabs);
                    }
                    SwingUtilities.updateComponentTreeUI(gcreator.window.consolepopup);
                    gcreator.window.look = 1;
                    Aurwindow.workspace.updateUI();
                    break;
                case 2:
                    UIManager.setLookAndFeel("com.sun.java.swing.plaf.motif.MotifLookAndFeel");
                    SwingUtilities.updateComponentTreeUI(gcreator.window);
                    if (gcreator.window.istabs) {
                        SwingUtilities.updateComponentTreeUI(gcreator.window.mdi);
                    } else {
                        SwingUtilities.updateComponentTreeUI(Aurwindow.tabs);
                    }
                    SwingUtilities.updateComponentTreeUI(gcreator.window.consolepopup);
                    gcreator.window.look = 2;
                    Aurwindow.workspace.updateUI();
                    break;
                case 3:
                    javax.swing.plaf.metal.MetalLookAndFeel.setCurrentTheme(new javax.swing.plaf.metal.DefaultMetalTheme());
                    UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
                    SwingUtilities.updateComponentTreeUI(gcreator.window);
                    if (gcreator.window.istabs) {
                        SwingUtilities.updateComponentTreeUI(gcreator.window.mdi);
                    } else {
                        SwingUtilities.updateComponentTreeUI(Aurwindow.tabs);
                    }
                    SwingUtilities.updateComponentTreeUI(gcreator.window.consolepopup);
                    gcreator.window.look = 3;
                    Aurwindow.workspace.updateUI();
                    break;
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        int sel = jComboBox2.getSelectedIndex();

        if (sel < 4) {
            if (!gcreator.window.istabs) {
                int k = gcreator.window.splitter2.getDividerLocation();
                gcreator.window.tabs.setVisible(true);
                gcreator.window.mdi.setVisible(false);
                if (gcreator.window.isWorkspaceLeft()) {
                    gcreator.window.splitter2.setRightComponent(gcreator.window.tabs);
                    if (gcreator.window.splitter2.getRightComponent().isVisible()) {
                        gcreator.window.splitter2.setDividerLocation(k);
                    }
                } else {
                    gcreator.window.splitter2.setLeftComponent(gcreator.window.tabs);
                    if (gcreator.window.splitter2.getLeftComponent().isVisible()) {
                        gcreator.window.splitter2.setDividerLocation(k);
                    }
                }
                gcreator.window.istabs = true;
                for (int i = 0; i < gcreator.window.mdi.getDesktop().getComponents().length; i++) {
                    if (!(gcreator.window.mdi.getDesktop().getComponent(i) instanceof ExtendedFrame)) {
                        continue;
                    }
                    try {
                        TabPanel panel = ((ExtendedFrame) gcreator.window.mdi.getDesktop().getComponent(i)).getPanel();
                        gcreator.window.tabs.addTab(panel.title, panel);
                        int ver = Integer.parseInt(org.gcreator.core.gcreator.getJavaVersion().replaceAll("1\\.([0-9])\\..*", "$1"));
                        if (ver >= 6) {
                            gcreator.window.tabs.setTabComponentAt(gcreator.window.tabs.indexOfComponent(panel), new ButtonTabComponent(gcreator.window.tabs));
                        }
                    } catch (ClassCastException e) {
                    }
                }
            }
        }

        try {
            switch (sel) {
                case 0:
                    gcreator.window.tabs.setTabPlacement(JTabbedPane.TOP);
                    break;
                case 1:
                    gcreator.window.tabs.setTabPlacement(JTabbedPane.LEFT);
                    break;
                case 2:
                    gcreator.window.tabs.setTabPlacement(JTabbedPane.BOTTOM);
                    break;
                case 3:
                    gcreator.window.tabs.setTabPlacement(JTabbedPane.RIGHT);
                    break;
            }
        } catch (Exception e) {
        }

        if(sel==4)
        if (gcreator.window.istabs) {
            int k = gcreator.window.splitter2.getDividerLocation();
            gcreator.window.tabs.setVisible(false);
            gcreator.window.mdi.setVisible(true);
            if (gcreator.window.isWorkspaceLeft()) {
                gcreator.window.splitter2.setRightComponent(gcreator.window.mdi);
                if (gcreator.window.splitter2.getRightComponent().isVisible()) {
                    gcreator.window.splitter2.setDividerLocation(k);
                }
            } else {
                gcreator.window.splitter2.setLeftComponent(gcreator.window.mdi);
                if (gcreator.window.splitter2.getLeftComponent().isVisible()) {
                    gcreator.window.splitter2.setDividerLocation(k);
                }
            }

            gcreator.window.istabs = false;
            Component[] panels = gcreator.window.tabs.getComponents();
            for (int i = 0; i < panels.length; i++) {
                if (panels[i] instanceof TabPanel) {
                    TabPanel panel = (TabPanel) panels[i];
                    org.jdesktop.layout.GroupLayout jInternalFrame1Layout = (org.jdesktop.layout.GroupLayout) panel.frame.getContentPane().getLayout();
                    jInternalFrame1Layout.setHorizontalGroup(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                    jInternalFrame1Layout.setVerticalGroup(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                }
            }
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        Aurwindow.antialiasing = jCheckBox1.isSelected();
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
