/*
 * Copyright (C) 2007-2008 Luís Reis <luiscubal@gmail.com>
 * Copyright (C) 2007-2008 TGMG <thegamemakerguru@hotmail.com>
 * Copyright (c) 2008 BobSerge or Bobistaken <serge_1994@hotmail.com>
 * 
 * This file is part of G-Creator.
 * G-Creator is free software and comes with ABSOLUTELY NO WARRANTY.
 * See LICENSE for more details.
 */
package org.gcreator.components;

import java.awt.*;

/**
 *
 * @author Luís Reis
 */
public class Statusbar extends javax.swing.JPanel {
    
    /** Creates new form Statusbar */
    public Statusbar() {
        initComponents();
    }
    
    private String text = "Text";
    
    public void setText(String text){
        jLabel1.setText(text);
    }
    
    public void restoreText(){
        jLabel1.setText(text);
    }
    
    public void setStandardText(String text){
        this.text = text;
    }
    
    public String getStandardText(){
        return text;
    }
    
    public ExtendedProgressBar getProgressBar(){
        return extendedProgressBar1;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        extendedProgressBar1 = new org.gcreator.components.ExtendedProgressBar();

        jLabel5.setText("jLabel5");

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        setMaximumSize(new java.awt.Dimension(2147483647, 20));
        setMinimumSize(new java.awt.Dimension(50, 20));
        setPreferredSize(new java.awt.Dimension(175, 20));
        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Text");
        add(jLabel1, java.awt.BorderLayout.LINE_START);

        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(extendedProgressBar1, java.awt.BorderLayout.LINE_END);

        add(jPanel1, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.gcreator.components.ExtendedProgressBar extendedProgressBar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}
