/*
 * WelcomeTab.java
 *
 * Created on 24 de Agosto de 2007, 17:23
 */
package org.gcreator.components;

import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import org.gcreator.core.GPanel;
import org.gcreator.core.gcreator;
import org.gcreator.fileclass.GameProject;
import org.gcreator.fileclass.Project;
//import org.gcreator.macro.Macro;
import org.gcreator.managers.*;

/**
 *
 * @author  Luís
 */
public class WelcomeTab extends TabPanel {

    /** Creates new form WelcomeTab */
    public WelcomeTab() {
        initComponents();
        jLabel1.setText(LangSupporter.activeLang.getEntry(37));
        jLabel2.setText(LangSupporter.activeLang.getEntry(38));
        //Graphics g = i.getImage().getGraphics();
        //j = new ImageIcon(new BufferedImage(400, 400, BufferedImage.TYPE_4BYTE_ABGR));
        jToggleButton1.setSelected(!new File("settings/disable_welcome").exists());

    }
    //private ImageIcon j = null;
    private ImageIcon i = new ImageIcon(WelcomeTab.class.getResource("/org/gcreator/resources/initgrad.png"));

    public void paint(Graphics _g) {
        Graphics2D g = (Graphics2D) _g;
        //DarkGradientPainter.paint(g, getWidth(), getHeight());
        /*g.drawImage(i.getImage(),
        0, 0, getWidth(), getHeight(),
        100, 100, 380, 380,
        i.getImageObserver());*/
        g.drawImage(i.getImage(), 0, 0, getWidth(), getHeight(), i.getImageObserver());
        super.paintChildren(g);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSSBlogReadPanel1 = new org.gcreator.components.RSSBlogReadPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rSSReadPanel1 = new org.gcreator.components.RSSReadPanel();
        rSSBlogReadPanel2 = new org.gcreator.components.RSSBlogReadPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome to Aurora,");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("The Next Generation of G-Creator");

        jToggleButton1.setText("Show welcome screen on start.");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/gcreator/resources/toolbar/new_game.png"))); // NOI18N
        jButton1.setText("Create new Empty Game");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, rSSBlogReadPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(jLabel1)
                                .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jToggleButton1))
                            .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 228, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 60, Short.MAX_VALUE)
                        .add(rSSReadPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel2)
                        .add(18, 18, 18)
                        .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 71, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 139, Short.MAX_VALUE)
                        .add(jToggleButton1))
                    .add(rSSReadPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(rSSBlogReadPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 195, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
    try {
        if (jToggleButton1.isSelected()) {
            new File("settings/disable_welcome").delete();
        } else {
            new File("settings/disable_welcome").createNewFile();
        }
    } catch (Exception e) {
    }
}//GEN-LAST:event_jToggleButton1ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Project project = null;
    project = GameProject.balance(ProjectTypes.EMPTY_GAME);
    project.name = "NewGame";
    project.location = "";
    GPanel.setMainProject(project);
    ProjectTree.importFolderToTree(project, gcreator.panel.top);
    /*Macro.macroAction(
                        "project = org.gcreator.fileclass.GameProject.balance("
                        + "org.gcreator.components.ProjectTypes.EMPTY_GAME);\n"
                        + "project.name = \"" + project.name + "\";\n"
                        + "project.location = \"\";\n"
                        + "org.gcreator.core.GPanel.setMainProject(project);\n"
                        + "org.gcreator.managers.ProjectTree.importFolderToTree("
                        + "project, org.gcreator.core.gcreator.panel.top);\n");*/
    try {
        gcreator.panel.workspace.updateUI();
    } catch (Exception e) {
    }
}//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToggleButton jToggleButton1;
    private org.gcreator.components.RSSBlogReadPanel rSSBlogReadPanel1;
    private org.gcreator.components.RSSBlogReadPanel rSSBlogReadPanel2;
    private org.gcreator.components.RSSReadPanel rSSReadPanel1;
    // End of variables declaration//GEN-END:variables
}
