#
#Wed May 09 20:31:39 BST 2007
icon32=org/gjava/actoreditor/actions/images/GM.011.gif
displayName=Jump to a given position
icon16=org/gjava/actoreditor/actions/images/GM.011.gif
args={//Start Parenthesis required\nint arg_x \= 0;\nint arg_y \= 0;\nboolean relative \= false;\nActor applies \= this;
code=if (relative)\r\n{\r\n    applies.x \= applies.x + arg_x;\r\n    applies.y \= applies.y + arg_y;\r\n}\r\nelse\r\n    {\r\n    applies.x \= arg_x;\r\n    applies.y \= arg_y;\r\n}\r\n}
id=id1
comment=Jump to a given position
