id=action_dest_instance
displayName=Destroy an instance
icon16=org/gjava/actoreditor/actions/destinstanc.png
icon32=org/gjava/actoreditor/actions/destinstanc.png
comment=Destroy an instance
code={ \
me=2; \
}
arg1=
arg2=
arg3=
arg4=