id=action_move_set_hor
displayName=Set the Horizontal Speed
icon16=org/gjava/actoreditor/actions/sethorizspeed.png
icon32=org/gjava/actoreditor/actions/sethorizspeed.png
comment=Start Moving
code={ \
me=2; \
}
arg1=
arg2=
arg3=
arg4=