#
#Wed May 09 18:28:16 BST 2007
icon32=org/gjava/actoreditor/actions/images/GM.066.gif
displayName=End of a block
args=//End of a block, don't add anything here otherwise it won't work\!
icon16=org/gjava/actoreditor/actions/images/GM.066.gif
code=}
comment=This is an Action
id=id1
