#
#Mon Jun 18 02:27:38 BST 2007
code=}
comment=End of a block
args=//End of a block, don't add anything here otherwise it won't work\!
displayName=End of a block
caption7=
caption6=
caption5=
arg7=
caption4=
arg6=
caption3=
arg5=
caption2=
arg4=
caption1=
arg3=
caption0=
arg2=
arg1=
arg0=
icon32=org/gjava/actoreditor/actions/images/GM.066.gif
id=id1
applies=false
description=<html>Indicates the end of a block of actions. </html>
icon16=org/gjava/actoreditor/actions/images/GM.066.gif
relative=false
