/*
 * WelcomePanel.java
 *
 * Created on 19 de Junho de 2007, 15:22
 */

package org.gjava.welcome.html;

import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.HyperlinkEvent;
import javax.swing.event.HyperlinkListener;
import javax.swing.text.html.HTMLDocument;
import org.openide.util.Exceptions;

/**
 *
 * @author  Porfirio
 */
public class WelcomePanel extends javax.swing.JTextPane{
    
    /** Creates new form WelcomePanel */
    public WelcomePanel() {
        initComponents();
        
        try {
            setPage(getClass().getResource("welcome.html"));
            System.out.println(((HTMLDocument)getDocument()).getElement("FeedContainer"));
            getDocument().addDocumentListener(new DocumentListener() {
                public void insertUpdate(DocumentEvent e) {System.out.println(((HTMLDocument)getDocument()).getElement("FeedContainer"));}
                public void removeUpdate(DocumentEvent e) {System.out.println(((HTMLDocument)getDocument()).getElement("FeedContainer"));}
                public void changedUpdate(DocumentEvent e) {System.out.println(((HTMLDocument)getDocument()).getElement("FeedContainer"));}
            });
        } catch (IOException ex) {
            Exceptions.printStackTrace(ex);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setContentType("text/html"); // NOI18N
        setEditable(false);
        addHyperlinkListener(new javax.swing.event.HyperlinkListener() {
            public void hyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {
                formHyperlinkUpdate(evt);
            }
        });
    }// </editor-fold>//GEN-END:initComponents
    
private void formHyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {//GEN-FIRST:event_formHyperlinkUpdate
    System.out.println(((HTMLDocument)getDocument()).getElement("FeedContainer"));
    if (evt.getEventType()== HyperlinkEvent.EventType.ACTIVATED){
        String url=evt.getDescription();
        if (url.toLowerCase().startsWith("goto:")){
            url=url.replace("goto:", "");
            try {
                org.openide.awt.HtmlBrowser.URLDisplayer.getDefault().showURL(new URL(url));
            } catch (MalformedURLException ex) {
                Exceptions.printStackTrace(ex);
            }
        }
    }
    
}//GEN-LAST:event_formHyperlinkUpdate



    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
