/*
 * RTFEditor.java
 *
 * Created on 30 de Julho de 2008, 13:02
 */

package org.gcreator.editors;

import com.l2fprod.common.swing.JFontChooser;
import java.awt.Font;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import javax.swing.event.CaretEvent;
import javax.swing.event.CaretListener;
import javax.swing.text.AttributeSet;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import javax.swing.text.rtf.RTFEditorKit;
import org.gcreator.components.RSSReader.StringInputStream;
import org.gcreator.components.TabPanel;
import org.gcreator.fileclass.GFile;
import org.gcreator.fileclass.Project;

/**
 *
 * @author  luis
 */
public class RTFEditor extends TabPanel {

    private RTFEditorKit kit = new RTFEditorKit();
    private boolean changed = false;
    
    /** Creates new form RTFEditor */
    public RTFEditor(Project p, GFile f) {
        project = p;
        file = f;
        initComponents();
        try{
            if(f.value!=null)
                jEditorPane1.read(new ByteArrayInputStream(f.value.toString().getBytes()), kit);
            else
                changed = true;
        }
        catch(Exception e){
            
        }
        jEditorPane1.addCaretListener(new CaretListener(){
            public void caretUpdate(CaretEvent e){
                updateBtn();
            }
        });
        updateBtn();
    }
    
    private void updateBtn(){
        int sel = jEditorPane1.getSelectionStart();
        jButton1.setSelected(getBoolProperty(sel, StyleConstants.Bold));
        jButton2.setSelected(getBoolProperty(sel, StyleConstants.Italic));
        jButton3.setSelected(getBoolProperty(sel, StyleConstants.Underline));
        Font f = new Font(getStringProperty(sel, StyleConstants.FontFamily),
                (getBoolProperty(sel, StyleConstants.Bold)?Font.BOLD:0)
                | (getBoolProperty(sel, StyleConstants.Italic)?Font.ITALIC:0),
                getIntProperty(sel, StyleConstants.FontSize));
        jButton4.setFont(f);
    }
    
    public boolean getBoolProperty(int index, Object prop){
        StyledDocument d = (StyledDocument) jEditorPane1.getDocument();
        Object o = d.getCharacterElement(index).getAttributes().getAttribute(prop);
        return o!=null&&o instanceof Boolean ? (Boolean) o : false;
    }
    
    public String getStringProperty(int index, Object prop){
        StyledDocument d = (StyledDocument) jEditorPane1.getDocument();
        Object o = d.getCharacterElement(index).getAttributes().getAttribute(prop);
        return o!=null&&o instanceof String ? (String) o : null;
    }
    
    public Integer getIntProperty(int index, Object prop){
        StyledDocument d = (StyledDocument) jEditorPane1.getDocument();
        Object o = d.getCharacterElement(index).getAttributes().getAttribute(prop);
        return o!=null&&o instanceof Integer ? (Integer) o : null;
    }

    public boolean wasModified(){
        return changed;
    }
    
    public boolean canSave(){
        return changed;
    }
    
    public boolean Save(){
        ByteArrayOutputStream s = new ByteArrayOutputStream();
        try{
            kit.write(s, jEditorPane1.getDocument(), 0, jEditorPane1.getDocument().getLength());
            file.value = s.toString();
            changed = false;
        }
        catch(Exception e){
            return false;
        }
        return true;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jEditorPane1.setBackground(java.awt.Color.white);
        jEditorPane1.setEditorKit(kit);
        jEditorPane1.setForeground(java.awt.Color.black);
        jScrollPane1.setViewportView(jEditorPane1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jToolBar1.setRollover(true);

        jButton1.setFont(jButton1.getFont().deriveFont(jButton1.getFont().getStyle() | java.awt.Font.BOLD));
        jButton1.setText("B");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setFont(jButton2.getFont().deriveFont((jButton2.getFont().getStyle() | java.awt.Font.ITALIC)));
        jButton2.setText("I");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton3.setText("<html><u>U");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jButton4.setText("Font");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        add(jToolBar1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    StyledDocument d = (StyledDocument) jEditorPane1.getDocument();
    int start = jEditorPane1.getSelectionStart();
    int end = jEditorPane1.getSelectionEnd();
    SimpleAttributeSet s = new SimpleAttributeSet();
    s.addAttribute(StyleConstants.Bold, !jButton1.isSelected());
    d.setCharacterAttributes(start, end-start, s, false);
    updateBtn();
    changed = true;
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    StyledDocument d = (StyledDocument) jEditorPane1.getDocument();
    int start = jEditorPane1.getSelectionStart();
    int end = jEditorPane1.getSelectionEnd();
    SimpleAttributeSet s = new SimpleAttributeSet();
    s.addAttribute(StyleConstants.Italic, !jButton2.isSelected());
    d.setCharacterAttributes(start, end-start, s, false);
    updateBtn();
    changed = true;
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    StyledDocument d = (StyledDocument) jEditorPane1.getDocument();
    int start = jEditorPane1.getSelectionStart();
    int end = jEditorPane1.getSelectionEnd();
    SimpleAttributeSet s = new SimpleAttributeSet();
    s.addAttribute(StyleConstants.Underline, !jButton3.isSelected());
    d.setCharacterAttributes(start, end-start, s, false);
    updateBtn();
    changed = true;
}//GEN-LAST:event_jButton3ActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    JFontChooser fc = new JFontChooser();
    fc.setSelectedFont(jButton4.getFont());
    Font f = fc.showFontDialog(this, "F");
    if(f!=null){
        StyledDocument d = (StyledDocument) jEditorPane1.getDocument();
        int start = jEditorPane1.getSelectionStart();
        int end = jEditorPane1.getSelectionEnd();
        SimpleAttributeSet s = new SimpleAttributeSet();
        s.addAttribute(StyleConstants.FontFamily, f.getFamily());
        s.addAttribute(StyleConstants.FontSize, f.getSize());
        s.addAttribute(StyleConstants.Bold, f.isBold());
        s.addAttribute(StyleConstants.Italic, f.isItalic());
        d.setCharacterAttributes(start, end-start, s, false);
        updateBtn();
        changed = true;
    }
}//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

}
