/*
 * RTFEditor.java
 *
 * Created on 30 de Julho de 2008, 13:02
 */

package org.gcreator.editors;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import javax.swing.event.CaretEvent;
import javax.swing.event.CaretListener;
import javax.swing.text.AttributeSet;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import javax.swing.text.rtf.RTFEditorKit;
import org.gcreator.components.RSSReader.StringInputStream;
import org.gcreator.components.TabPanel;
import org.gcreator.fileclass.GFile;
import org.gcreator.fileclass.Project;

/**
 *
 * @author  luis
 */
public class RTFEditor extends TabPanel {

    private RTFEditorKit kit = new RTFEditorKit();
    private boolean changed = false;
    
    /** Creates new form RTFEditor */
    public RTFEditor(Project p, GFile f) {
        project = p;
        file = f;
        initComponents();
        try{
            if(f.value!=null)
                jEditorPane1.read(new ByteArrayInputStream(f.value.toString().getBytes()), kit);
            else
                changed = true;
        }
        catch(Exception e){
            
        }
        jEditorPane1.addCaretListener(new CaretListener(){
            public void caretUpdate(CaretEvent e){
                updateBtn();
            }
        });
    }
    
    private void updateBtn(){
        int sel = jEditorPane1.getSelectionStart();
        jButton1.setSelected(getProperty(sel, StyleConstants.Bold));
    }
    
    public boolean getProperty(int index, Object prop){
        StyledDocument d = (StyledDocument) jEditorPane1.getDocument();
        Object o = d.getCharacterElement(index).getAttributes().getAttribute(prop);
        return o!=null&&o instanceof Boolean ? (Boolean) o : false;
    }

    public boolean wasModified(){
        return changed;
    }
    
    public boolean canSave(){
        return changed;
    }
    
    public boolean Save(){
        ByteArrayOutputStream s = new ByteArrayOutputStream();
        try{
            kit.write(s, jEditorPane1.getDocument(), 0, jEditorPane1.getDocument().getLength());
            file.value = s.toString();
            changed = false;
        }
        catch(Exception e){
            return false;
        }
        return true;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jEditorPane1.setBackground(java.awt.Color.white);
        jEditorPane1.setEditorKit(kit);
        jEditorPane1.setForeground(java.awt.Color.black);
        jScrollPane1.setViewportView(jEditorPane1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jToolBar1.setRollover(true);

        jButton1.setFont(jButton1.getFont().deriveFont(jButton1.getFont().getStyle() | java.awt.Font.BOLD));
        jButton1.setText("B");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        add(jToolBar1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    StyledDocument d = (StyledDocument) jEditorPane1.getDocument();
    int start = jEditorPane1.getSelectionStart();
    int end = jEditorPane1.getSelectionEnd();
    SimpleAttributeSet s = new SimpleAttributeSet();
    s.addAttribute(StyleConstants.Bold, !jButton1.isSelected());
    d.setCharacterAttributes(start, end-start, s, false);
    updateBtn();
    changed = true;
}//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

}
