/*
 * RTFEditor.java
 *
 * Created on 30 de Julho de 2008, 13:02
 */
package org.gcreator.editors;

import com.l2fprod.common.swing.JFontChooser;
import java.awt.Color;
import java.awt.Font;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.event.CaretEvent;
import javax.swing.event.CaretListener;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import javax.swing.text.rtf.RTFEditorKit;
import org.gcreator.components.TabPanel;
import org.gcreator.components.impl.CustomFileFilter;
import org.gcreator.fileclass.GFile;
import org.gcreator.fileclass.Project;

/**
 *
 * @author  luis
 */
public class RTFEditor extends TabPanel {

    private RTFEditorKit kit = new RTFEditorKit();
    private boolean changed = false;

    /** Creates new form RTFEditor */
    public RTFEditor(Project p, GFile f) {
        project = p;
        file = f;
        initComponents();
        try {
            if (f.value != null) {
                jEditorPane1.read(new ByteArrayInputStream(f.value.toString().getBytes()), kit);
            } else {
                changed = true;
            }
        } catch (Exception e) {

        }
        jEditorPane1.addCaretListener(new CaretListener() {

            @Override
            public void caretUpdate(CaretEvent e) {
                updateBtn();
            }
        });

        updateBtn();
    }

    private void updateBtn() {
        int sel = jEditorPane1.getSelectionStart();
        jButton1.setSelected(getBoolProperty(sel, StyleConstants.Bold));
        jButton2.setSelected(getBoolProperty(sel, StyleConstants.Italic));
        jButton3.setSelected(getBoolProperty(sel, StyleConstants.Underline));
        jButton5.setBackground(getColorProperty(sel, StyleConstants.Foreground));
        jButton6.setBackground(getColorProperty(sel, StyleConstants.Background));
    }

    public boolean getBoolProperty(int index, Object prop) {
        StyledDocument d = (StyledDocument) jEditorPane1.getDocument();
        Object o = d.getCharacterElement(index).getAttributes().getAttribute(prop);
        return o != null && o instanceof Boolean ? (Boolean) o : false;
    }

    public Color getColorProperty(int index, Object prop) {
        StyledDocument d = (StyledDocument) jEditorPane1.getDocument();
        Object o = d.getCharacterElement(index).getAttributes().getAttribute(prop);
        return o != null && o instanceof Color ? (Color) o : null;
    }

    public String getStringProperty(int index, Object prop) {
        StyledDocument d = (StyledDocument) jEditorPane1.getDocument();
        Object o = d.getCharacterElement(index).getAttributes().getAttribute(prop);
        return o != null && o instanceof String ? (String) o : null;
    }

    public Integer getIntProperty(int index, Object prop) {
        StyledDocument d = (StyledDocument) jEditorPane1.getDocument();
        Object o = d.getCharacterElement(index).getAttributes().getAttribute(prop);
        return o != null && o instanceof Integer ? (Integer) o : null;
    }

    @Override
    public boolean wasModified() {
        return changed;
    }

    @Override
    public boolean canSave() {
        return changed;
    }

    @Override
    public boolean Save() {
        ByteArrayOutputStream s = new ByteArrayOutputStream();
        try {
            kit.write(s, jEditorPane1.getDocument(), 0, jEditorPane1.getDocument().getLength());
            file.value = s.toString();
            changed = false;
        } catch (Exception e) {
            return false;
        }
        return true;
    }
    
    @Override
    public boolean setModified(boolean a) {
        changed = a;
        return true;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton8 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        saveResourcePanel1 = new org.gcreator.components.SaveResourcePanel(this);

        jButton8.setText("jButton8");

        setLayout(new java.awt.BorderLayout());

        jEditorPane1.setBackground(new java.awt.Color(255, 255, 255));
        jEditorPane1.setEditorKit(kit);
        jScrollPane1.setViewportView(jEditorPane1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jToolBar1.setRollover(true);

        jButton1.setText("<html><b>B");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setFont(jButton2.getFont().deriveFont((jButton2.getFont().getStyle() | java.awt.Font.ITALIC)));
        jButton2.setText("<html><i>I</i>");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton3.setText("<html><u>U</u></html>");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jLabel3.setText("<html><!--Layout fix -->");
        jToolBar1.add(jLabel3);

        jLabel4.setText("<html><!--Layout fix -->");
        jToolBar1.add(jLabel4);

        jLabel5.setText("<html><!--Layout fix -->");
        jToolBar1.add(jLabel5);

        jLabel6.setText("<html><!--Layout fix -->");
        jToolBar1.add(jLabel6);

        jButton4.setText("Font");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        jLabel1.setText("Foreground:");
        jToolBar1.add(jLabel1);

        jButton5.setText("    ");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);

        jLabel2.setText("Background:");
        jToolBar1.add(jLabel2);

        jButton6.setText("    ");
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton6);

        jButton7.setText("Import");
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton7);

        jButton9.setText("Export");
        jButton9.setFocusable(false);
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton9);

        add(jToolBar1, java.awt.BorderLayout.PAGE_START);
        add(saveResourcePanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    StyledDocument d = (StyledDocument) jEditorPane1.getDocument();
    int start = jEditorPane1.getSelectionStart();
    int end = jEditorPane1.getSelectionEnd();
    SimpleAttributeSet s = new SimpleAttributeSet();
    s.addAttribute(StyleConstants.Bold, !jButton1.isSelected());
    d.setCharacterAttributes(start, end - start, s, false);
    updateBtn();
    changed = true;
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    StyledDocument d = (StyledDocument) jEditorPane1.getDocument();
    int start = jEditorPane1.getSelectionStart();
    int end = jEditorPane1.getSelectionEnd();
    SimpleAttributeSet s = new SimpleAttributeSet();
    s.addAttribute(StyleConstants.Italic, !jButton2.isSelected());
    d.setCharacterAttributes(start, end - start, s, false);
    updateBtn();
    changed = true;
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    StyledDocument d = (StyledDocument) jEditorPane1.getDocument();
    int start = jEditorPane1.getSelectionStart();
    int end = jEditorPane1.getSelectionEnd();
    SimpleAttributeSet s = new SimpleAttributeSet();
    s.addAttribute(StyleConstants.Underline, !jButton3.isSelected());
    d.setCharacterAttributes(start, end - start, s, false);
    updateBtn();
    changed = true;
}//GEN-LAST:event_jButton3ActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    JFontChooser fc = new JFontChooser();
    fc.setSelectedFont(jButton4.getFont());
    Font f = fc.showFontDialog(this, "F");
    if (f != null) {
        StyledDocument d = (StyledDocument) jEditorPane1.getDocument();
        int start = jEditorPane1.getSelectionStart();
        int end = jEditorPane1.getSelectionEnd();
        SimpleAttributeSet s = new SimpleAttributeSet();
        s.addAttribute(StyleConstants.FontFamily, f.getFamily());
        s.addAttribute(StyleConstants.FontSize, f.getSize());
        s.addAttribute(StyleConstants.Bold, f.isBold());
        s.addAttribute(StyleConstants.Italic, f.isItalic());
        d.setCharacterAttributes(start, end - start, s, false);
        updateBtn();
        changed = true;
    }
}//GEN-LAST:event_jButton4ActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    Color c = JColorChooser.showDialog(this, "Choose", jButton5.getBackground());
    if (c != null) {
        StyledDocument d = (StyledDocument) jEditorPane1.getDocument();
        int start = jEditorPane1.getSelectionStart();
        int end = jEditorPane1.getSelectionEnd();
        SimpleAttributeSet s = new SimpleAttributeSet();
        s.addAttribute(StyleConstants.Foreground, c);
        d.setCharacterAttributes(start, end - start, s, false);
        updateBtn();
        changed = true;
    }
}//GEN-LAST:event_jButton5ActionPerformed

private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    Color c = JColorChooser.showDialog(this, "Choose", jButton6.getBackground());
    if (c != null) {
        StyledDocument d = (StyledDocument) jEditorPane1.getDocument();
        int start = jEditorPane1.getSelectionStart();
        int end = jEditorPane1.getSelectionEnd();
        SimpleAttributeSet s = new SimpleAttributeSet();
        s.addAttribute(StyleConstants.Background, c);
        d.setCharacterAttributes(start, end - start, s, false);
        updateBtn();
        changed = true;
    }
}//GEN-LAST:event_jButton6ActionPerformed

private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    JFileChooser d = new JFileChooser();
    d.setApproveButtonText("OK");
    d.setAcceptAllFileFilterUsed(true);
    d.addChoosableFileFilter(new CustomFileFilter(".rtf", "Rich Text files"));
    d.setDialogTitle("Choose RTF file");
    d.setMultiSelectionEnabled(false);
    d.showDialog(this, "OK");
    d.setDialogType(JFileChooser.FILES_ONLY | JFileChooser.OPEN_DIALOG);
    File f = d.getSelectedFile();
    if (f != null) {
        try {
            jEditorPane1.read(new FileInputStream(f), kit);
            changed = true;
        } catch (Exception e) {

        }
    }
}//GEN-LAST:event_jButton7ActionPerformed

private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
    JFileChooser d = new JFileChooser();
    d.setApproveButtonText("OK");
    d.setAcceptAllFileFilterUsed(true);
    d.addChoosableFileFilter(new CustomFileFilter(".rtf", "Rich Text files"));
    d.setDialogTitle("Where to save RTF file?");
    d.setMultiSelectionEnabled(false);
    d.showDialog(this, "OK");
    d.setDialogType(JFileChooser.FILES_ONLY | JFileChooser.SAVE_DIALOG);
    File f = d.getSelectedFile();
    if (f != null) {
        try {
            kit.write(new FileOutputStream(f), jEditorPane1.getDocument(), 0, jEditorPane1.getDocument().getLength());
        } catch (Exception e) {

        }
    }
}//GEN-LAST:event_jButton9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private org.gcreator.components.SaveResourcePanel saveResourcePanel1;
    // End of variables declaration//GEN-END:variables

}
