/*
 * SnippetEditor.java
 *
 * Created on 8 de Junho de 2008, 13:24
 */

package org.gcreator.editors;

import javax.swing.event.*;
import org.gcreator.components.*;
import org.gcreator.core.*;
import org.gcreator.fileclass.*;
import org.gcreator.fileclass.res.*;

/**
 *
 * @author  Luís
 */
public class SnippetEditor extends TabPanel {

    private Snippet snippet = null;
    private boolean changed = false;
    
    /** Creates new form SnippetEditor */
    public SnippetEditor(Project p, GFile f) {
        this.file = f;
        this.project = p;
        
        if(f.value==null){
            snippet = new Snippet();
            changed = true;
        }
        else{
            snippet = (Snippet) ((Snippet) f.value).clone();
        }
        
        initComponents();
        jTextField1.setText(f.name);
        jTextField1.getDocument().addDocumentListener(new DocumentListener(){
            @Override
            public void changedUpdate(DocumentEvent e){
                update();
            }
            
            @Override
            public void removeUpdate(DocumentEvent e){
                update();
            }
            
            @Override
            public void insertUpdate(DocumentEvent e){
                update();
            }
            
            public void update(){
                file.name = jTextField1.getText();
                gcreator.panel.workspace.updateUI();
            }
        });
    }

    @Override
    public boolean wasModified(){
        return changed;
    }
    
    @Override
    public boolean canSave(){
        return changed;
    }
    
    @Override
    public boolean Save(){
        file.value = snippet;
        changed = false;
        return true;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        jLabel1.setText("Name:");

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(307, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(249, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
